=== matsim-org/matsim-libs/matsim/dtd/counts_v1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xml:lang="en">

<xsd:element name="counts" type="countsType"/>
	

<xsd:complexType name="countsType">	
	<xsd:sequence>
		<xsd:element name="count" type="countType" minOccurs="1" maxOccurs="unbounded"/>
	</xsd:sequence>
	<xsd:attribute name="name" type="xsd:string" use="required"/>
	<xsd:attribute name="desc" type="xsd:string" use="optional"/>
	<xsd:attribute name="year" type="xsd:gYear" use="required"/>
	<xsd:attribute name="layer" type="xsd:string" use="optional"/><!-- deprecated, should no longer be used. -->
</xsd:complexType>

<xsd:complexType name="countType">
	<xsd:sequence>
		<xsd:element name="volume" type="volumeType" minOccurs="1" maxOccurs="unbounded"/>
	</xsd:sequence>
	<xsd:attribute name="loc_id" type="xsd:string" use="required"/>
	<xsd:attribute name="cs_id" type="xsd:string" use="optional" default="0"/>
	<xsd:attribute name="x" type="xsd:double" use="optional"/>
	<xsd:attribute name="y" type="xsd:double" use="optional"/>
</xsd:complexType>

<xsd:complexType name="volumeType">
	<xsd:attribute name="h" type="xsd:positiveInteger" use="required"/>
	<xsd:attribute name="val" type="positiveFloat" use="required"/>
</xsd:complexType>

<xsd:simpleType name="positiveFloat">
	<xsd:restriction base="xsd:float">
		<xsd:minInclusive value="0.0"/>
	</xsd:restriction>
</xsd:simpleType>
</xsd:schema>

=== matsim-org/matsim-libs/playgrounds/mmoyo/test/input/playground/mmoyo/cadyts_integration/ptBseAsPlanStrategy/CadytsIntegrationTest/testCalibration/counts/counts_occupancy.xml
<?xml version="1.0" encoding="UTF-8"?>
<counts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="http://matsim.org/files/dtd/counts_v1.xsd"
 name="occupancyCounts" desc="counts values for equil net" year="2010"  layer="0" 
>
<!-- ====================================================================== -->
	<count loc_id="stop1" cs_id="stop1" x="-15000" y="0" >
		<volume h="1" val="0.00" />
		<volume h="2" val="0.00" />
		<volume h="3" val="0.00" />
		<volume h="4" val="0.00" />
		<volume h="5" val="0.00" />
		<volume h="6" val="0.00" />
		<volume h="7" val="4.00" />
		<volume h="8" val="0.00" />
		<volume h="9" val="0.00" />
		<volume h="10" val="0.00" />
		<volume h="11" val="0.00" />
		<volume h="12" val="0.00" />
		<volume h="13" val="0.00" />
		<volume h="14" val="0.00" />
		<volume h="15" val="0.00" />
		<volume h="16" val="0.00" />
		<volume h="17" val="0.00" />
		<volume h="18" val="0.00" />
		<volume h="19" val="0.00" />
		<volume h="20" val="0.00" />
		<volume h="21" val="0.00" />
		<volume h="22" val="0.00" />
		<volume h="23" val="0.00" />
		<volume h="24" val="0.00" />
	</count>
	
	<count loc_id="stop2" cs_id="stop2" x="-865" y="5925" >
		<volume h="1" val="0.00" />
		<volume h="2" val="0.00" />
		<volume h="3" val="0.00" />
		<volume h="4" val="0.00" />
		<volume h="5" val="0.00" />
		<volume h="6" val="0.00" />
		<volume h="7" val="1.00" />
		<volume h="8" val="0.00" />
		<volume h="9" val="0.00" />
		<volume h="10" val="0.00" />
		<volume h="11" val="0.00" />
		<volume h="12" val="0.00" />
		<volume h="13" val="0.00" />
		<volume h="14" val="0.00" />
		<volume h="15" val="0.00" />
		<volume h="16" val="0.00" />
		<volume h="17" val="0.00" />
		<volume h="18" val="0.00" />
		<volume h="19" val="0.00" />
		<volume h="20" val="0.00" />
		<volume h="21" val="0.00" />
		<volume h="22" val="0.00" />
		<volume h="23" val="0.00" />
		<volume h="24" val="0.00" />
	</count>

	<count loc_id="stop6" cs_id="stop6" x="-5000" y="0" >
		<volume h="1" val="0.00" />
		<volume h="2" val="0.00" />
		<volume h="3" val="0.00" />
		<volume h="4" val="0.00" />
		<volume h="5" val="0.00" />
		<volume h="6" val="0.00" />
		<volume h="7" val="2.00" />
		<volume h="8" val="0.00" />
		<volume h="9" val="0.00" />
		<volume h="10" val="0.00" />
		<volume h="11" val="0.00" />
		<volume h="12" val="0.00" />
		<volume h="13" val="0.00" />
		<volume h="14" val="0.00" />
		<volume h="15" val="0.00" />
		<volume h="16" val="0.00" />
		<volume h="17" val="0.00" />
		<volume h="18" val="0.00" />
		<volume h="19" val="0.00" />
		<volume h="20" val="0.00" />
		<volume h="21" val="0.00" />
		<volume h="22" val="0.00" />
		<volume h="23" val="0.00" />
		<volume h="24" val="0.00" />
	</count>
	
	<count loc_id="stop10" cs_id="stop10" x="-865" y="-5925" >
		<volume h="1" val="0.00" />
		<volume h="2" val="0.00" />
		<volume h="3" val="0.00" />
		<volume h="4" val="0.00" />
		<volume h="5" val="0.00" />
		<volume h="6" val="0.00" />
		<volume h="7" val="1.00" />
		<volume h="8" val="0.00" />
		<volume h="9" val="0.00" />
		<volume h="10" val="0.00" />
		<volume h="11" val="0.00" />
		<volume h="12" val="0.00" />
		<volume h="13" val="0.00" />
		<volume h="14" val="0.00" />
		<volume h="15" val="0.00" />
		<volume h="16" val="0.00" />
		<volume h="17" val="0.00" />
		<volume h="18" val="0.00" />
		<volume h="19" val="0.00" />
		<volume h="20" val="0.00" />
		<volume h="21" val="0.00" />
		<volume h="22" val="0.00" />
		<volume h="23" val="0.00" />
		<volume h="24" val="0.00" />
	</count>

</counts>

=== matsim-org/matsim-libs/contribs/cadytsIntegration/src/test/resources/test/input/org/matsim/contrib/cadyts/car/CadytsCarIT/counts5.xml
<?xml version="1.0" encoding="UTF-8"?>

<counts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://matsim.org/files/dtd/counts_v1.xsd" 
		name="equilCounts" desc="counts values for equil net" 
		year="2008" layer="0">
	<!-- in a equilibrium state, there should be the same amount of vehicles
		 on the 9 alternative routes.  100 vehicles / 9 routes = 11.1 veh/route -->
	<count loc_id="11" cs_id="link_11">
		<volume h="1" val="0" />
		<volume h="2" val="0" />
		<volume h="3" val="0" />
		<volume h="4" val="0" />
		<volume h="5" val="0" />
		<volume h="6" val="0" />
		<volume h="7" val="0" />
		<volume h="8" val="0" />
		<volume h="9" val="0" />
		<volume h="10" val="0" />
		<volume h="11" val="0" />
		<volume h="12" val="0" />
		<volume h="13" val="0" />
		<volume h="14" val="0" />
		<volume h="15" val="0" />
		<volume h="16" val="0" />
		<volume h="17" val="0" />
		<volume h="18" val="0" />
		<volume h="19" val="0" />
		<volume h="20" val="0" />
		<volume h="21" val="0" />
		<volume h="22" val="0" />
		<volume h="23" val="0" />
		<volume h="24" val="0" />
	</count>
	<count loc_id="12" cs_id="link_12">
		<volume h="1" val="0" />
		<volume h="2" val="0" />
		<volume h="3" val="0" />
		<volume h="4" val="0" />
		<volume h="5" val="0" />
		<volume h="6" val="0" />
		<volume h="7" val="0" />
		<volume h="8" val="0" />
		<volume h="9" val="0" />
		<volume h="10" val="0" />
		<volume h="11" val="0" />
		<volume h="12" val="0" />
		<volume h="13" val="0" />
		<volume h="14" val="0" />
		<volume h="15" val="0" />
		<volume h="16" val="0" />
		<volume h="17" val="0" />
		<volume h="18" val="0" />
		<volume h="19" val="0" />
		<volume h="20" val="0" />
		<volume h="21" val="0" />
		<volume h="22" val="0" />
		<volume h="23" val="0" />
		<volume h="24" val="0" />
	</count>
	<count loc_id="13" cs_id="link_13">
		<volume h="1" val="0" />
		<volume h="2" val="0" />
		<volume h="3" val="0" />
		<volume h="4" val="0" />
		<volume h="5" val="0" />
		<volume h="6" val="0" />
		<volume h="7" val="0" />
		<volume h="8" val="0" />
		<volume h="9" val="0" />
		<volume h="10" val="0" />
		<volume h="11" val="0" />
		<volume h="12" val="0" />
		<volume h="13" val="0" />
		<volume h="14" val="0" />
		<volume h="15" val="0" />
		<volume h="16" val="0" />
		<volume h="17" val="0" />
		<volume h="18" val="0" />
		<volume h="19" val="0" />
		<volume h="20" val="0" />
		<volume h="21" val="0" />
		<volume h="22" val="0" />
		<volume h="23" val="0" />
		<volume h="24" val="0" />
	</count>
	<count loc_id="14" cs_id="link_14">
		<volume h="1" val="0" />
		<volume h="2" val="0" />
		<volume h="3" val="0" />
		<volume h="4" val="0" />
		<volume h="5" val="0" />
		<volume h="6" val="0" />
		<volume h="7" val="0" />
		<volume h="8" val="0" />
		<volume h="9" val="0" />
		<volume h="10" val="0" />
		<volume h="11" val="0" />
		<volume h="12" val="0" />
		<volume h="13" val="0" />
		<volume h="14" val="0" />
		<volume h="15" val="0" />
		<volume h="16" val="0" />
		<volume h="17" val="0" />
		<volume h="18" val="0" />
		<volume h="19" val="0" />
		<volume h="20" val="0" />
		<volume h="21" val="0" />
		<volume h="22" val="0" />
		<volume h="23" val="0" />
		<volume h="24" val="0" />
	</count>
	<count loc_id="15" cs_id="link_15">
		<volume h="1" val="0" />
		<volume h="2" val="0" />
		<volume h="3" val="0" />
		<volume h="4" val="0" />
		<volume h="5" val="0" />
		<volume h="6" val="0" />
		<volume h="7" val="0" />
		<volume h="8" val="0" />
		<volume h="9" val="0" />
		<volume h="10" val="0" />
		<volume h="11" val="0" />
		<volume h="12" val="0" />
		<volume h="13" val="0" />
		<volume h="14" val="0" />
		<volume h="15" val="0" />
		<volume h="16" val="0" />
		<volume h="17" val="0" />
		<volume h="18" val="0" />
		<volume h="19" val="0" />
		<volume h="20" val="0" />
		<volume h="21" val="0" />
		<volume h="22" val="0" />
		<volume h="23" val="0" />
		<volume h="24" val="0" />
	</count>
	<count loc_id="16" cs_id="link_16">
		<volume h="1" val="0" />
		<volume h="2" val="0" />
		<volume h="3" val="0" />
		<volume h="4" val="0" />
		<volume h="5" val="0" />
		<volume h="6" val="0" />
		<volume h="7" val="0" />
		<volume h="8" val="0" />
		<volume h="9" val="0" />
		<volume h="10" val="0" />
		<volume h="11" val="0" />
		<volume h="12" val="0" />
		<volume h="13" val="0" />
		<volume h="14" val="0" />
		<volume h="15" val="0" />
		<volume h="16" val="0" />
		<volume h="17" val="0" />
		<volume h="18" val="0" />
		<volume h="19" val="0" />
		<volume h="20" val="0" />
		<volume h="21" val="0" />
		<volume h="22" val="0" />
		<volume h="23" val="0" />
		<volume h="24" val="0" />
	</count>
	<count loc_id="17" cs_id="link_17">
		<volume h="1" val="0" />
		<volume h="2" val="0" />
		<volume h="3" val="0" />
		<volume h="4" val="0" />
		<volume h="5" val="0" />
		<volume h="6" val="0" />
		<volume h="7" val="0" />
		<volume h="8" val="0" />
		<volume h="9" val="0" />
		<volume h="10" val="0" />
		<volume h="11" val="0" />
		<volume h="12" val="0" />
		<volume h="13" val="0" />
		<volume h="14" val="0" />
		<volume h="15" val="0" />
		<volume h="16" val="0" />
		<volume h="17" val="0" />
		<volume h="18" val="0" />
		<volume h="19" val="0" />
		<volume h="20" val="0" />
		<volume h="21" val="0" />
		<volume h="22" val="0" />
		<volume h="23" val="0" />
		<volume h="24" val="0" />
	</count>
	<count loc_id="18" cs_id="link_18">
		<volume h="1" val="0" />
		<volume h="2" val="0" />
		<volume h="3" val="0" />
		<volume h="4" val="0" />
		<volume h="5" val="0" />
		<volume h="6" val="0" />
		<volume h="7" val="0" />
		<volume h="8" val="0" />
		<volume h="9" val="0" />
		<volume h="10" val="0" />
		<volume h="11" val="0" />
		<volume h="12" val="0" />
		<volume h="13" val="0" />
		<volume h="14" val="0" />
		<volume h="15" val="0" />
		<volume h="16" val="0" />
		<volume h="17" val="0" />
		<volume h="18" val="0" />
		<volume h="19" val="0" />
		<volume h="20" val="0" />
		<volume h="21" val="0" />
		<volume h="22" val="0" />
		<volume h="23" val="0" />
		<volume h="24" val="0" />
	</count>
	<count loc_id="19" cs_id="link_19">
		<volume h="1" val="0" />
		<volume h="2" val="0" />
		<volume h="3" val="0" />
		<volume h="4" val="0" />
		<volume h="5" val="0" />
		<volume h="6" val="0" />
		<volume h="7" val="5" />
		<volume h="8" val="0" />
		<volume h="9" val="0" />
		<volume h="10" val="0" />
		<volume h="11" val="0" />
		<volume h="12" val="0" />
		<volume h="13" val="0" />
		<volume h="14" val="0" />
		<volume h="15" val="0" />
		<volume h="16" val="0" />
		<volume h="17" val="0" />
		<volume h="18" val="0" />
		<volume h="19" val="0" />
		<volume h="20" val="0" />
		<volume h="21" val="0" />
		<volume h="22" val="0" />
		<volume h="23" val="0" />
		<volume h="24" val="0" />
	</count>
	<count loc_id="21" cs_id="link_21">
		<volume h="1" val="0" />
		<volume h="2" val="0" />
		<volume h="3" val="0" />
		<volume h="4" val="0" />
		<volume h="5" val="0" />
		<volume h="6" val="0" />
		<volume h="7" val="5" />
		<volume h="8" val="0" />
		<volume h="9" val="0" />
		<volume h="10" val="0" />
		<volume h="11" val="0" />
		<volume h="12" val="0" />
		<volume h="13" val="0" />
		<volume h="14" val="0" />
		<volume h="15" val="0" />
		<volume h="16" val="0" />
		<volume h="17" val="0" />
		<volume h="18" val="0" />
		<volume h="19" val="0" />
		<volume h="20" val="0" />
		<volume h="21" val="0" />
		<volume h="22" val="0" />
		<volume h="23" val="0" />
		<volume h="24" val="0" />
	</count>
</counts>
