=== matsim-org/matsim-libs/contribs/carsharing/src/main/resources/dtd/CSMembership.dtd
<?xml version="1.0" encoding="utf-8"?>

<!-- $Id$ -->

<!-- ============================================================ -->
<!ELEMENT memberships          (person*)>
<!ATTLIST memberships
          name           CDATA   #IMPLIED
          reference_layer  CDATA #IMPLIED
          xml:lang       NMTOKEN "de-CH">


<!ELEMENT person          (company*)>
<!ATTLIST person
          id           CDATA   #IMPLIED>   

<!ELEMENT company          (carsharing*)>
<!ATTLIST company
          id           CDATA   #REQUIRED>
          

<!ELEMENT carsharing         EMPTY>
<!ATTLIST carsharing
          name           CDATA   #REQUIRED>

=== matsim-org/matsim-libs/contribs/carsharing/test/input/org/matsim/contrib/carsharing/runExample/RunCarsharingIT/CSMembership.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE memberships SYSTEM "src/main/resources/dtd/CSMembership.dtd">
<memberships>
	<person id="0">
		<company id="Mobility">
			<carsharing name="twoway"/>
			<carsharing name="oneway"/>
			<carsharing name="freefloating"/>
		</company>
	</person>
	<person id="1">
		<company id="Mobility">
			<carsharing name="twoway"/>
			<carsharing name="oneway"/>
			<carsharing name="freefloating"/>
		</company>
	</person>
	<person id="10">
		<company id="Mobility">
			<carsharing name="twoway"/>
			<carsharing name="oneway"/>
			<carsharing name="freefloating"/>
		</company>
	</person>
	<person id="100">
		<company id="Mobility">
			<carsharing name="twoway"/>
			<carsharing name="oneway"/>
			<carsharing name="freefloating"/>
		</company>
	</person>
	<person id="101">
		<company id="Mobility">
			<carsharing name="twoway"/>
			<carsharing name="oneway"/>
			<carsharing name="freefloating"/>
		</company>
	</person>
	<person id="102">
		<company id="Mobility">
			<carsharing name="twoway"/>
			<carsharing name="oneway"/>
			<carsharing name="freefloating"/>
		</company>
	</person>
	<person id="103">
		<company id="Mobility">
			<carsharing name="twoway"/>
			<carsharing name="oneway"/>
			<carsharing name="freefloating"/>
		</company>
	</person>
	<person id="104">
		<company id="Mobility">
			<carsharing name="twoway"/>
			<carsharing name="oneway"/>
			<carsharing name="freefloating"/>
		</company>
	</person>
	<person id="105">
		<company id="Mobility">
			<carsharing name="twoway"/>
			<carsharing name="oneway"/>
			<carsharing name="freefloating"/>
		</company>
	</person>
	<person id="106">
		<company id="Mobility">
			<carsharing name="twoway"/>
			<carsharing name="oneway"/>
			<carsharing name="freefloating"/>
		</company>
	</person>
</memberships>
