=== matsim-org/matsim-libs/matsim/src/main/resources/dtd/electric_vehicles_v1.dtd
<?xml version="1.0" encoding="utf-8"?>

<!-- ============================================================ -->

<!-- For further information or questions, please contact
     Michal Maciejewski, maciejewski at vsp dot tu-berlin dot de -->

<!-- ============================================================ -->

<!ELEMENT vehicles (vehicle)*>

<!ELEMENT vehicle EMPTY>

<!-- initial_soc - in kWh -->
<!-- battery_capacity - in kWh -->
<!-- charger_types - supported charger types; comma-separated list; "default" if not provided) -->
<!-- vehicle_type - "defaultVehicleType" if not provided -->
<!ATTLIST vehicle
	id CDATA #REQUIRED
	initial_soc CDATA #REQUIRED
	battery_capacity CDATA #REQUIRED
	charger_types CDATA #IMPLIED
	vehicle_type CDATA #IMPLIED>

=== matsim-org/matsim-libs/src/main/resources/mielec_2014_02/etaxis-25.xml
<?xml version="1.0" ?>
<!DOCTYPE vehicles SYSTEM "http://matsim.org/files/dtd/electric_vehicles_v1.dtd">

<vehicles>
	<vehicle id="taxi_1_1" battery_capacity="20" initial_soc="16.0"/>
	<vehicle id="taxi_1_2" battery_capacity="20" initial_soc="14.0"/>
	<vehicle id="taxi_1_3" battery_capacity="20" initial_soc="12.0"/>
	<vehicle id="taxi_1_4" battery_capacity="20" initial_soc="10.0"/>
	<vehicle id="taxi_1_5" battery_capacity="20" initial_soc="8.0"/>
	<vehicle id="taxi_2_1" battery_capacity="20" initial_soc="15.5"/>
	<vehicle id="taxi_2_2" battery_capacity="20" initial_soc="13.5"/>
	<vehicle id="taxi_2_3" battery_capacity="20" initial_soc="11.5"/>
	<vehicle id="taxi_2_4" battery_capacity="20" initial_soc="9.5"/>
	<vehicle id="taxi_2_5" battery_capacity="20" initial_soc="7.5"/>
	<vehicle id="taxi_3_1" battery_capacity="20" initial_soc="15.0"/>
	<vehicle id="taxi_3_2" battery_capacity="20" initial_soc="13.0"/>
	<vehicle id="taxi_3_3" battery_capacity="20" initial_soc="11.0"/>
	<vehicle id="taxi_3_4" battery_capacity="20" initial_soc="9.0"/>
	<vehicle id="taxi_3_5" battery_capacity="20" initial_soc="7.0"/>
	<vehicle id="taxi_4_1" battery_capacity="20" initial_soc="14.5"/>
	<vehicle id="taxi_4_2" battery_capacity="20" initial_soc="12.5"/>
	<vehicle id="taxi_4_3" battery_capacity="20" initial_soc="10.5"/>
	<vehicle id="taxi_4_4" battery_capacity="20" initial_soc="8.5"/>
	<vehicle id="taxi_4_5" battery_capacity="20" initial_soc="6.5"/>
	<vehicle id="taxi_5_1" battery_capacity="20" initial_soc="14.0"/>
	<vehicle id="taxi_5_2" battery_capacity="20" initial_soc="12.0"/>
	<vehicle id="taxi_5_3" battery_capacity="20" initial_soc="10.0"/>
	<vehicle id="taxi_5_4" battery_capacity="20" initial_soc="8.0"/>
	<vehicle id="taxi_5_5" battery_capacity="20" initial_soc="6.0"/>
</vehicles>
