=== matsim-org/matsim-libs/matsim/src/main/resources/dtd/facilities_v1.dtd
<?xml version="1.0" encoding="utf-8"?>

        <!-- $Id$ -->

        <!-- ============================================================ -->

        <!-- For further information or questions, please contact
             Michael Balmer, balmermi at inf dot ethz dot ch -->

        <!-- ============================================================ -->

        <!ELEMENT facilities        (attributes?,facility*)>
        <!ATTLIST facilities
                name              CDATA   #IMPLIED
                aggregation_layer CDATA   #IMPLIED
                xml:lang          NMTOKEN "de-CH">

        <!ELEMENT facility   (activity*,attributes?)>
        <!ATTLIST facility
                id         CDATA #REQUIRED
                x          CDATA #IMPLIED
                y          CDATA #IMPLIED
                linkId     CDATA #IMPLIED
                desc       CDATA #IMPLIED>

        <!ELEMENT activity   (capacity?,opentime*)>
        <!ATTLIST activity
                type       CDATA #REQUIRED>

        <!ELEMENT capacity   EMPTY>
        <!ATTLIST capacity
                value      CDATA #REQUIRED>

        <!ELEMENT opentime   EMPTY>
        <!ATTLIST opentime
                day        (mon|tue|wed|thu|fri|sat|sun|wkday|wkend|wk) "wk"
                start_time CDATA                                        #REQUIRED
                end_time   CDATA                                        #REQUIRED>

        <!ELEMENT attributes        (attribute*)>

        <!ELEMENT attribute     ANY>
        <!ATTLIST attribute
                name          CDATA #REQUIRED
                class         CDATA #REQUIRED>


        <!-- ============================================================ -->

        <!-- ROOT ELEMENT facilities:
             Landuse data at the level of single organizations: shops, companies, houses. -->

        <!-- ATTRIBUTE name:
             The name should describe of which kind of data this
             file holds. I.e. "Kanton Zurich - from database xyz".
             format: string -->
        <!-- ATTRIBUTE xml:lang:
             Used by i.e. Java to know how to format and parse
             times, dates, etc. according to a given locale (e.g. en_US, de_CH) -->

        <!-- ============================================================ -->

        <!-- ELEMENT facility:
             A spatially aggregate organization where persons can perform activities.
             The coordinate system of the x,y coordinates has to be specified in a
             world file. -->

        <!-- ATTRIBUTE id:
             Identification of a facility -->

        <!-- ATTRIBUTE x:
             x-coordinate of that facility.
             format: real number -->

        <!-- ATTRIBUTE y:
             y-coordinate of that facility.
             format: real number -->

        <!-- ATTRIBUTE linkId:
             id of a link in a network, on which this facility can be reached. -->

        <!-- ============================================================ -->

        <!-- ELEMENT activity:
             Defines spatial and temporal properties for
             a specific activity to be performed in a zone. -->

        <!-- ATTRIBUTE type:
             Activity type, e.g. work or shop.
             format: string (can only be chosen from given values) -->

        <!-- ============================================================ -->

        <!-- ELEMENT capacity:
             A cell can hold a limited capacity per activity.
             A capacity is the maximum number of something in a given time range,
             e.g. number of costumers shopping at the same time or number of
             workplaces.
             If this element is not specified, then the capacity of the defined
             activity is unlimited. -->

        <!-- ATTRIBUTE value:
             Value of the capacity.
             format: unsigned integer -->

        <!-- ============================================================ -->

        <!-- ELEMENT opentime:
             Each zone/activity combination can hold a variable amount of opening
             times describing on what times the facility is open and therefore
             accessible.
             The opening times are specified on a daily basis for maximum week periods.
             If no opentime element is specified, the facility is closed all the time.
             To make a facility open all the time, include the following opentime
             element:
             <opentime day="wk" start_time="00:00" end_time="24:00" /> -->

        <!-- ATTRIBUTE day:
             A schedule can be set for a single day, for all weekdays,
             the weekend or for the whole week. Schedules for single days always
             override schedules for time ranges, e.g. a "mon" schedule for
             Monday overrides weekday or whole week schedules.

             ATTENTION: for a given facility, schedules must
             not overlap in time. I.e.
               <opentime day="mon" start_time="09:00" end_time="14:00" />
               <opentime day="mon" start_time="11:00" end_time="18:00" />
             is not allowed.
             mon - Monday
             tue - Tuesday
             wed - Wednesday
             thu - Thursday
             fri - Friday
             sat - Saturday
             sun - Sunday
             wkday - week days (mon through fri)
             wkend - week end (sat, sun)
             wk - whole week (mon through sun)
             format: string (can only be chosen from given values) -->

        <!-- ATTRIBUTE start_time:
             Defines when a facility opens.
             format: compatible with the locale defined in xml:lang -->

        <!-- ATTRIBUTE end_time:
             Defines when a facility closes.
             format: compatible with the locale defined in xml:lang -->

        <!-- If start_time > end_time, then the facility is opened over
             midnight. -->

        <!-- ============================================================ -->

=== matsim-org/matsim-libs/contribs/carsharing/test/input/org/matsim/contrib/carsharing/runExample/RunCarsharingTests/facilities.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE facilities SYSTEM "http://www.matsim.org/files/dtd/facilities_v1.dtd">

<facilities name="barbell facilities">

<!-- ====================================================================== -->
         <facility id="0" x="0.0" y="-375.0">
                  <activity type="h">
                  </activity>
         </facility>
<!-- ====================================================================== -->
         <facility id="1" x="-375.0" y="0.0">
                  <activity type="h">
                  </activity>
         </facility>
<!-- ====================================================================== -->
         <facility id="2" x="0.0" y="375.0">
                  <activity type="h">
                  </activity>
         </facility>
<!-- ====================================================================== -->
         <facility id="3" x="1000.0" y="-250.0">
                  <activity type="w">
                  </activity>
         </facility>
<!-- ====================================================================== -->
          <facility id="4" x="1250.0" y="0.0">
                   <activity type="w">
                   </activity>
         </facility>
<!-- ====================================================================== -->
         <facility id="5" x="1000.0" y="250.0">
                  <activity type="w">
                  </activity>
         </facility>
<!-- ====================================================================== -->
	
</facilities>
