=== matsim-org/matsim-libs/matsim/src/main/resources/dtd/freightReceivers_v2.dtd
<?xml version="1.0" encoding="utf-8"?>

<!-- $Id$ -->

<!-- =============================================================== -->
<!-- Author: jwjoubert, wlbean                                       -->
<!-- Revised dtd-file for freight-contrib's receiver agent           -->
<!-- =============================================================== -->

<!ELEMENT freightReceivers  (attributes?, productTypes*, receiver*)> 
<!ATTLIST freightReceivers
          desc              CDATA           #IMPLIED>

<!ELEMENT attributes        (attribute*)>

<!ELEMENT attribute         (#PCDATA)>
<!ATTLIST attribute
          name              CDATA           #REQUIRED
          class             CDATA           #REQUIRED>

<!ELEMENT productTypes      (productType*)>

<!ELEMENT productType       (#PCDATA)>
<!ATTLIST productType  
        id                  CDATA           #REQUIRED
		originLinkId		CDATA			#REQUIRED
        descr               CDATA           #IMPLIED
        weight              CDATA           #IMPLIED>

<!ELEMENT receiver 			(attributes?, product*, plan*)>
<!ATTLIST receiver
        id                  CDATA           #REQUIRED
        linkId              CDATA           #IMPLIED>
		
<!ELEMENT product           (reorderPolicy?, order*)>
<!ATTLIST product
        id                  CDATA           #REQUIRED
        onHand              CDATA           #IMPLIED>

<!ELEMENT reorderPolicy     (attributes?)>
<!ATTLIST reorderPolicy
        name                CDATA           #REQUIRED>

<!ELEMENT plan			(timeWindow*, order*)>
<!ATTLIST plan
		score				CDATA			#IMPLIED
		selected			CDATA			#REQUIRED>

<!ELEMENT timeWindow        (#PCDATA)>
<!ATTLIST timeWindow
        start               CDATA           #REQUIRED
        end                 CDATA           #REQUIRED>
		

<!ELEMENT order             (item*)>
<!ATTLIST order
        carrierId           CDATA           #REQUIRED>

<!ELEMENT item              (#PCDATA)>
<!ATTLIST item
        id                  CDATA           #REQUIRED
        name                CDATA           #IMPLIED
        productId           CDATA           #REQUIRED
        quantity            CDATA           #IMPLIED
        serviceTime         CDATA           #IMPLIED>


<!-- ============================================================ -->
         
<!-- ATTRIBUTE id is required and needs to be unique. They may include:
     Letters (lower or capital)
     Numbers 0 to 9
     Punctuation marks: 
     	_ (underscore), 
     	- (single hyphen),
     	. (Dot) and
     	: (colon) - however, the colon is reserved for page namespaces

	The first character of a name can not be a number, it must be a letter or one of the 
	allowed punctuation marks. 
	In practice, the first character should always be a letter or if needed an underscore.
	Spaces are NOT allowed. -->

=== matsim-org/matsim-libs/contribs/freightreceiver/test/input/org/matsim/freight/receiver/ReceiversReaderTest/receivers_v2_full.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE freightReceivers SYSTEM "https://matsim.org/files/dtd/freightReceivers_v2.dtd">

<freightReceivers desc="Chessboard">
	<attributes>
		<attribute name="date" class="java.lang.String" >2019/02/09 00:11:29</attribute>
	</attributes>

	<productTypes>
		<productType id="P1" originLinkId="j(1,7)" descr="Product 1" weight="1.0"/>
		<productType id="P2" originLinkId="j(1,7)" descr="Product 2" weight="2.0"/>
	</productTypes>

	<!-- =========================================================================================== -->

	<receiver id="1" linkId="i(7,9)R">
		<attributes>
			<attribute name="collaborationStatus" class="java.lang.Boolean" >true</attribute>
			<attribute name="grandCoalitionMember" class="java.lang.Boolean" >true</attribute>
			<attribute name="score" class="java.lang.Double" >-19428.336</attribute>
		</attributes>
		<product id="P1" onHand="0.00">
			<reorderPolicy name="(s,S)">
				<attributes>
					<attribute name="S" class="java.lang.Double" >5000.0</attribute>
					<attribute name="s" class="java.lang.Double" >1000.0</attribute>
				</attributes>
			</reorderPolicy>
		</product>
		<product id="P2" onHand="0.00">
			<reorderPolicy name="(s,S)">
				<attributes>
					<attribute name="S" class="java.lang.Double" >2500.0</attribute>
					<attribute name="s" class="java.lang.Double" >500.0</attribute>
				</attributes>
			</reorderPolicy>
		</product>
		<plan score="-19428.336" selected="no">
			<timeWindow start="06:00:00" end="18:00:00"/>
			<order carrierId="Carrier1">
				<item id="Order11" productId="P1" quantity="5000.0" serviceTime="04:00:00"/>
				<item id="Order12" productId="P2" quantity="2500.0" serviceTime="04:00:00"/>
			</order>
		</plan>
		<plan score="-19428.336" selected="no">
			<timeWindow start="06:00:00" end="18:00:00"/>
			<order carrierId="Carrier1">
				<item id="Order11" productId="P1" quantity="5000.0" serviceTime="04:00:00"/>
				<item id="Order12" productId="P2" quantity="2500.0" serviceTime="04:00:00"/>
			</order>
		</plan>
		<plan score="-19428.336" selected="no">
			<timeWindow start="06:00:00" end="18:00:00"/>
			<order carrierId="Carrier1">
				<item id="Order11" productId="P1" quantity="5000.0" serviceTime="01:00:00"/>
				<item id="Order12" productId="P2" quantity="2500.0" serviceTime="01:00:00"/>
			</order>
		</plan>
		<plan score="-19428.336" selected="no">
			<timeWindow start="06:00:00" end="18:00:00"/>
			<order carrierId="Carrier1">
				<item id="Order11" productId="P1" quantity="5000.0" serviceTime="03:00:00"/>
				<item id="Order12" productId="P2" quantity="2500.0" serviceTime="03:00:00"/>
			</order>
		</plan>
		<plan score="-19428.336" selected="yes">
			<timeWindow start="06:00:00" end="10:00:00"/>
			<timeWindow start="15:00:00" end="18:00:00"/>
			<order carrierId="Carrier1">
				<item id="Order11" productId="P1" quantity="5000.0" serviceTime="03:00:00"/>
				<item id="Order12" productId="P2" quantity="2500.0" serviceTime="03:00:00"/>
			</order>
		</plan>
	</receiver>

	<!-- =========================================================================================== -->

	<receiver id="2" linkId="j(4,2)R">
		<attributes>
			<attribute name="collaborationStatus" class="java.lang.Boolean" >true</attribute>
			<attribute name="grandCoalitionMember" class="java.lang.Boolean" >true</attribute>
		</attributes>
		<product id="P1" onHand="0.00">
			<reorderPolicy name="(s,S)">
				<attributes>
					<attribute name="S" class="java.lang.Double" >5000.0</attribute>
					<attribute name="s" class="java.lang.Double" >1000.0</attribute>
				</attributes>
			</reorderPolicy>
		</product>
		<product id="P2" onHand="0.00">
			<reorderPolicy name="(s,S)">
				<attributes>
					<attribute name="S" class="java.lang.Double" >2500.0</attribute>
					<attribute name="s" class="java.lang.Double" >500.0</attribute>
				</attributes>
			</reorderPolicy>
		</product>
		<plan selected="yes">
			<timeWindow start="06:00:00" end="18:00:00"/>
			<order carrierId="Carrier1">
				<item id="Order21" productId="P1" quantity="5000.0" serviceTime="02:30:00"/>
				<item id="Order22" productId="P2" quantity="2500.0" serviceTime="02:30:00"/>
			</order>
		</plan>
	</receiver>

	<!-- =========================================================================================== -->

	<receiver id="3" linkId="i(4,3)R">
		<attributes>
			<attribute name="collaborationStatus" class="java.lang.Boolean" >true</attribute>
			<attribute name="grandCoalitionMember" class="java.lang.Boolean" >true</attribute>
		</attributes>
		<product id="P1" onHand="0.00">
			<reorderPolicy name="(s,S)">
				<attributes>
					<attribute name="S" class="java.lang.Double" >5000.0</attribute>
					<attribute name="s" class="java.lang.Double" >1000.0</attribute>
				</attributes>
			</reorderPolicy>
		</product>
		<product id="P2" onHand="0.00">
			<reorderPolicy name="(s,S)">
				<attributes>
					<attribute name="S" class="java.lang.Double" >2500.0</attribute>
					<attribute name="s" class="java.lang.Double" >500.0</attribute>
				</attributes>
			</reorderPolicy>
		</product>
		<plan selected="yes">
			<timeWindow start="06:00:00" end="18:00:00"/>
			<order carrierId="Carrier1">
				<item id="Order31" productId="P1" quantity="5000.0" serviceTime="02:30:00"/>
				<item id="Order32" productId="P2" quantity="2500.0" serviceTime="02:30:00"/>
			</order>
		</plan>
	</receiver>

	<!-- =========================================================================================== -->

	<receiver id="4" linkId="j(4,9)R">
		<attributes>
			<attribute name="collaborationStatus" class="java.lang.Boolean" >true</attribute>
			<attribute name="grandCoalitionMember" class="java.lang.Boolean" >true</attribute>
		</attributes>
		<product id="P1" onHand="0.00">
			<reorderPolicy name="(s,S)">
				<attributes>
					<attribute name="S" class="java.lang.Double" >5000.0</attribute>
					<attribute name="s" class="java.lang.Double" >1000.0</attribute>
				</attributes>
			</reorderPolicy>
		</product>
		<product id="P2" onHand="0.00">
			<reorderPolicy name="(s,S)">
				<attributes>
					<attribute name="S" class="java.lang.Double" >2500.0</attribute>
					<attribute name="s" class="java.lang.Double" >500.0</attribute>
				</attributes>
			</reorderPolicy>
		</product>
		<plan selected="yes">
			<timeWindow start="06:00:00" end="18:00:00"/>
			<order carrierId="Carrier1">
				<item id="Order41" productId="P1" quantity="5000.0" serviceTime="02:30:00"/>
				<item id="Order42" productId="P2" quantity="2500.0" serviceTime="02:30:00"/>
			</order>
		</plan>
	</receiver>

	<!-- =========================================================================================== -->

	<receiver id="5" linkId="i(1,4)">
		<attributes>
			<attribute name="collaborationStatus" class="java.lang.Boolean" >true</attribute>
			<attribute name="grandCoalitionMember" class="java.lang.Boolean" >true</attribute>
		</attributes>
		<product id="P1" onHand="0.00">
			<reorderPolicy name="(s,S)">
				<attributes>
					<attribute name="S" class="java.lang.Double" >5000.0</attribute>
					<attribute name="s" class="java.lang.Double" >1000.0</attribute>
				</attributes>
			</reorderPolicy>
		</product>
		<product id="P2" onHand="0.00">
			<reorderPolicy name="(s,S)">
				<attributes>
					<attribute name="S" class="java.lang.Double" >2500.0</attribute>
					<attribute name="s" class="java.lang.Double" >500.0</attribute>
				</attributes>
			</reorderPolicy>
		</product>
		<plan selected="yes">
			<timeWindow start="06:00:00" end="18:00:00"/>
			<order carrierId="Carrier1">
				<item id="Order51" productId="P1" quantity="5000.0" serviceTime="02:30:00"/>
				<item id="Order52" productId="P2" quantity="2500.0" serviceTime="02:30:00"/>
			</order>
		</plan>
	</receiver>

	<!-- =========================================================================================== -->

</freightReceivers>
