=== matsim-org/matsim-libs/matsim/src/main/resources/dtd/networkChangeEvents.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.matsim.org/files/dtd"
					 xmlns="http://www.matsim.org/files/dtd"
					 elementFormDefault="qualified"
					 xmlns:xs="http://www.w3.org/2001/XMLSchema"
					 xml:lang="en">

<!-- Editor: Dominik Grether, VSP, Berlin Institute of Technology -->

<xs:include schemaLocation="http://www.matsim.org/files/dtd/matsimCommon.xsd"/>

<xs:element name="networkChangeEvents">
	<xs:annotation>
	<xs:documentation>Just a wrapper for the NetworkChangeEvents</xs:documentation>
	</xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element name="networkChangeEvent" type="networkChangeEventType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:complexType name="networkChangeEventType">
  <xs:sequence>
    <xs:element name="link" type="idRefType" minOccurs="1" maxOccurs="unbounded"/>
    <xs:element name="flowCapacity" type="changeType" minOccurs="0" maxOccurs="1"/>
    <xs:element name="freespeed" type="changeType" minOccurs="0" maxOccurs="1"/>
    <xs:element name="lanes" type="changeType" minOccurs="0" maxOccurs="1"/>
    <xs:element name="attribute" type="attributeChangeType" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attribute name="startTime" type="matsimFormattedTimeAttributeType" use="required"/>
</xs:complexType>

<xs:complexType name="changeType">
	<xs:attribute name="type">
		<xs:simpleType>
	  	<xs:restriction base="xs:string">
		    <xs:enumeration value="absolute" />
			  <xs:enumeration value="scaleFactor" />
			  <xs:enumeration value="offset" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="value" type="xs:double" use="required" />
</xs:complexType>

<xs:complexType name="attributeChangeType">
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute name="type">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="absolute" />
                <xs:enumeration value="scaleFactor" />
                <xs:enumeration value="offset" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="value" type="xs:double" use="required" />
</xs:complexType>

</xs:schema>

=== matsim-org/matsim-libs/contribs/railsim/test/input/ch/sbb/matsim/contrib/railsim/integration/microTrainFollowingFixedVsMovingBlock/events_capacityChange.xml
<?xml version="1.0" encoding="UTF-8"?>
<networkChangeEvents xmlns="http://www.matsim.org/files/dtd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.matsim.org/files/dtd http://www.matsim.org/files/dtd/networkChangeEvents.xsd">

	<!--Increase the fixed block capacity during train following -->
	<networkChangeEvent startTime="08:09:00">
		<link refId="t1_4-t1_5"/>
		<link refId="t1_5-t1_6"/>
		<link refId="t1_6-t1_7"/>

		<!-- Needs to be 3 with deadlock avoidance -->
		<attribute name="railsimTrainCapacity"  type="absolute" value="3"/>
	</networkChangeEvent>

	<!--Decrease the moving block capacity during train following -->
	<networkChangeEvent startTime="08:09:00">
		<link refId="t2_4-t2_5"/>
		<link refId="t2_5-t2_6"/>
		<link refId="t2_6-t2_7"/>

		<attribute name="railsimTrainCapacity"  type="absolute" value="0"/>
	</networkChangeEvent>

	<!--Increase again later -->
	<networkChangeEvent startTime="08:20:00">
		<link refId="t2_4-t2_5"/>
		<link refId="t2_5-t2_6"/>
		<link refId="t2_6-t2_7"/>

		<attribute name="railsimTrainCapacity"  type="absolute" value="3"/>
	</networkChangeEvent>

</networkChangeEvents>
