=== matsim-org/matsim-libs/matsim/src/main/resources/dtd/network_v2.dtd
<?xml version="1.0" encoding="utf-8"?>

<!-- ============================================================ -->

<!ELEMENT network (attributes?,nodes,links)>
<!ATTLIST network
          name       CDATA #IMPLIED>

<!ELEMENT attributes    (attribute*)>

<!ELEMENT attribute       (#PCDATA)>
<!ATTLIST attribute
          name        CDATA #REQUIRED
          class       CDATA #REQUIRED>

<!ELEMENT nodes (node)*>

<!ELEMENT links (link)*>
<!ATTLIST links capperiod  CDATA "01:00:00"
          effectivecellsize CDATA "7.5"
          effectivelanewidth CDATA "3.75">

<!ELEMENT node (attributes?)>
<!ATTLIST node id          CDATA #REQUIRED
               x           CDATA #REQUIRED
               y           CDATA #REQUIRED
               z           CDATA #IMPLIED
               type        CDATA #IMPLIED
               origid      CDATA #IMPLIED>

<!ELEMENT link (attributes?)>
<!ATTLIST link id          CDATA #REQUIRED
               from        CDATA #REQUIRED
               to          CDATA #REQUIRED
               length      CDATA #REQUIRED
               freespeed   CDATA #REQUIRED
               capacity    CDATA #REQUIRED
               permlanes   CDATA #REQUIRED
               oneway      CDATA #FIXED    "1"
               origid      CDATA #IMPLIED
               type        CDATA #IMPLIED
               modes       CDATA "car">

<!-- ============================================================ -->

<!-- ROOT ELEMENT network:
     The network describes nodes and links of a given region.
     It is spit up into three different networks: streets,
     pedestrians and publictransport.

     NOTE: At the moment (October 2004), Matsim only handles street
     networks (motorized individual transport). The others are
     included just for completeness. (They will be used in future.)
     -->

<!-- ATTRIBUTE name:
     It is always a good idea to give a network a descriptive
     name for better identification.
     Normally the name should describe the region which is described
     by the network (i.e. Switzerland, Berlin, ...).
     format := string -->
<!-- ATTRIBUTE type:
     description of the type of the network (i.e. motorized individual
     transport, public transport, etc.)
     format := string -->
<!-- ATTRIBUTE capDivider:
     This is the same as the attribute 'capperiod' in the links element.
     To be compatible with older scenarios, it is still there, but
     should be removed somewhen. Note that it holds only the hours!
     format := unsigned int
     units  := hour -->
<!-- ATTRIBUTE xml:lang:
     Defines the language settings (see xml spec). -->

<!-- ============================================================ -->

<!-- ELEMENT nodes:
     Holds all the nodes of the network. -->

<!-- ============================================================ -->

<!-- ELEMENT links:
     Holds all the links of the network. -->

<!-- ATTRIBUTE capperiod:
     format := "hh:mm:ss"
     meaning:  It defines the time period over which
               the capacity of the given links has been measured.
     NOTE:     It is "01:00:00" per default, i.e. 3600.0 sec   -->

<!-- ATTRIBUTE effectivecellsize:
     format := double
     meaning:  It defines the effective length of the cells in meters. The default value is 7.5 -->
     
<!-- ATTRIBUTE effectivelanewidth:
     format := double
     meaning:  It defines the effective width of a lane in meters. The default value is 3.75 -->     

<!-- ATTRIBUTE capDivider, capdivider and capPeriod:
     DEPRECATED!!!
     Do not use those attributes anymore. It will be ignored
     by matsim -->

<!-- ============================================================ -->

<!-- ELEMENT node:
     A node of the network. -->

<!-- ATTRIBUTE id:
     Each node HAS to have a unique id!
     format := unsigned integer -->

<!-- ATTRIBUTE x:
     Each node HAS to have an x coordinate!
     format := double
     units  := meter -->

<!-- ATTRIBUTE y:
     Each node HAS to have an y coordinate!
     format := double
     units  := meter -->

<!-- ATTRIBUTE type:
     Typically, networks are created by third party (i.e. GIS users).
     So it makes sense (for completeness) to add the type of the node.
     Note, sometimes, the type defines in which of the network categories
     it belongs (streets, pedestrians, publictransport), so be sure,
     that the type does not conflict with the network category.
     format := string -->

<!-- ============================================================ -->

<!-- ELEMENT link:
     A link of the network. -->

<!-- ATTRIBUTE id:
     Each link HAS to have a unique id!
     format := unsigned integer -->

<!-- ATTRIBUTE from:
     Each link HAS to have a fromnode-ID, which is part of the SAME
     network category as this link.
     format := unsigned integer -->

<!-- ATTRIBUTE to:
     Each link HAS to have a tonode-ID, which is part of the SAME network
     category as this link.
     format := unsigned integer -->

<!-- ATTRIBUTE length:
     Defines the real length of the link.  It must be (of course)
     at least as long as the Euclidean distance between
     the from and to nodes.
     format := unsigned double
     units  := meter -->

<!-- ATTRIBUTE freespeed:
     Defines the allowed maximum speed of the link (for street link).
     defines the 'fixed' speed of the link (for publictransport links).
     defines the 'typical' speed of the link (for pedestrian links).
     format := double
     units  := meter/seconds -->

<!-- ATTRIBUTE capacity:
     Defines the maximal capacity of this link for a given period (see
     ATTRIBUTE capperiod).
     format := double
     units  := vehicles/[given period] -->

<!-- ATTRIBUTE permlanes:
     Defines the number of lanes of this link.
     format := double 
     units  := N/A -->

<!-- ATTRIBUTE oneway:
     Matsim handles ONLY oneway links.  A bidirectional link has to be
     defined as two unidirectional links. -->

<!-- ATTRIBUTE modes:
     Comma-separated list of transportation modes that are allowed on
     this link. -->

<!-- The following attributes are special ones typically generated by
     VISUM. -->

<!-- ATTRIBUTE volume:
     If available, it is possible to add measured/counted average
     volume for this link.  It should respect the given period (see
     capperiod).
     format := double
     units  := vehicles/[given period] -->

<!-- ATTRIBUTE origid:
     Since other programs (i.e. VISUM) provide bidirectional links,
     those have to split up into two unidirectional links.  This
     attribute holds the original id for comparison.
     format := string
     units  := N/A -->

<!-- ATTRIBUTE nt_category:
     Sometimes networks provide different kinds of classification.
     It is possible to keep them there.
     format := string -->

<!-- ATTRIBUTE nt_type:
     Sometimes networks provide different kinds of classification.
     It is possible to keep them there.
     format := string -->

<!-- ATTRIBUTE type:
     Typically, networks are created by third party (i.e. GIS users).
     So it makes sense (for completeness) to add the type of the link.
     Note, sometimes, the type defines in which of the network
     categories it belongs (streets, pedestrians, publictransport), so
     be sure, that the type does not conflict with the network
     category.
     format := string -->

<!-- ============================================================ -->

=== matsim-org/matsim-libs/contribs/railsim/test/input/ch/sbb/matsim/contrib/railsim/integration/shuttle/trainNetwork.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE network SYSTEM "http://www.matsim.org/files/dtd/network_v2.dtd">
<network name="Shuttle Network">

	<attributes>
		<attribute name="coordinateReferenceSystem" class="java.lang.String">Atlantis</attribute>
	</attributes>
	<!-- ====================================================================== -->

	<!--
	Shuttle Network with Intermediate Station
	Main Stations: A - M - B (linear shuttle route)
	Intermediate Node: M (midpoint between A and B)
	Shuttle Route: A -> M -> B -> M -> A (back and forth)
	Stop Links: Dedicated links for train stops (150m length each) - bidirectional
	Extended route for 10-minute one-way travel time
	-->

	<nodes>
		<!-- Main stations forming a linear route -->
		<node id="node_A" x="0.0" y="0.0" />
		<node id="node_A_stop" x="150.0" y="0.0" />
		<node id="node_M" x="5000.0" y="0.0" />
		<node id="node_M_stop" x="5150.0" y="0.0" />
		<node id="node_B" x="10000.0" y="0.0" />
		<node id="node_B_stop" x="10150.0" y="0.0" />
	</nodes>

	<!-- ====================================================================== -->

	<links capperiod="01:00:00" effectivecellsize="7.5" effectivelanewidth="3.75">
		<!-- Stop links for train boarding/alighting - bidirectional -->
		<link id="link_A_to_stop" from="node_A" to="node_A_stop" length="150.0" freespeed="20.0" capacity="1000.0" permlanes="1.0" oneway="1" modes="rail">
			<attributes>
				<attribute name="railsimTrainCapacity" class="java.lang.Integer">2</attribute>
			</attributes>
		</link>
		<link id="link_A_from_stop" from="node_A_stop" to="node_A" length="150.0" freespeed="20.0" capacity="1000.0" permlanes="1.0" oneway="1" modes="rail">
			<attributes>
				<attribute name="railsimTrainCapacity" class="java.lang.Integer">2</attribute>
			</attributes>
		</link>
		<link id="link_M_to_stop" from="node_M" to="node_M_stop" length="150.0" freespeed="20.0" capacity="1000.0" permlanes="1.0" oneway="1" modes="rail">
			<attributes>
				<attribute name="railsimTrainCapacity" class="java.lang.Integer">2</attribute>
			</attributes>
		</link>
		<link id="link_M_from_stop" from="node_M_stop" to="node_M" length="150.0" freespeed="20.0" capacity="1000.0" permlanes="1.0" oneway="1" modes="rail">
			<attributes>
				<attribute name="railsimTrainCapacity" class="java.lang.Integer">2</attribute>
			</attributes>
		</link>
		<link id="link_B_to_stop" from="node_B" to="node_B_stop" length="150.0" freespeed="20.0" capacity="1000.0" permlanes="1.0" oneway="1" modes="rail">
			<attributes>
				<attribute name="railsimTrainCapacity" class="java.lang.Integer">2</attribute>
			</attributes>
		</link>
		<link id="link_B_from_stop" from="node_B_stop" to="node_B" length="150.0" freespeed="20.0" capacity="1000.0" permlanes="1.0" oneway="1" modes="rail">
			<attributes>
				<attribute name="railsimTrainCapacity" class="java.lang.Integer">2</attribute>
			</attributes>
		</link>
		
		<!-- Main route links -->
		<link id="link_AM" from="node_A_stop" to="node_M" length="5000.0" freespeed="20.0" capacity="1000.0" permlanes="1.0" oneway="1" modes="rail">
			<attributes>
				<attribute name="railsimTrainCapacity" class="java.lang.Integer">2</attribute>
			</attributes>
		</link>
		<link id="link_MB" from="node_M_stop" to="node_B" length="5000.0" freespeed="20.0" capacity="1000.0" permlanes="1.0" oneway="1" modes="rail">
			<attributes>
				<attribute name="railsimTrainCapacity" class="java.lang.Integer">2</attribute>
			</attributes>
		</link>
		<link id="link_BM" from="node_B" to="node_M_stop" length="5000.0" freespeed="20.0" capacity="1000.0" permlanes="1.0" oneway="1" modes="rail">
			<attributes>
				<attribute name="railsimTrainCapacity" class="java.lang.Integer">2</attribute>
			</attributes>
		</link>
		<link id="link_MA" from="node_M" to="node_A_stop" length="5000.0" freespeed="20.0" capacity="1000.0" permlanes="1.0" oneway="1" modes="rail">
			<attributes>
				<attribute name="railsimTrainCapacity" class="java.lang.Integer">2</attribute>
			</attributes>
		</link>
	</links>

	<!-- ====================================================================== -->

</network>

=== matsim-org/matsim-libs/contribs/bicycle/src/main/java/org/matsim/contrib/bicycle/run/scenarios/bicycle_example/network_MI_test2_stau.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE network SYSTEM "http://www.matsim.org/files/dtd/network_v2.dtd">
<network>

	<!-- ======================================================================
	  Simples Testnetzwerk fuer Ueberhol-Test Auto vs. Fahrrad.

	  Struktur:
	    Knoten 0 (Einfahr-Puffer) -> Knoten 1..10 (Teststrecke) -> Knoten 11 (Ausfahr-Puffer)

	  Die eigentlichen Test-Links sind IDs 1..9 (zwischen Knoten 1 und 10).
	  Links ID 0 (Einfahrt) und ID 10 (Ausfahrt) sind Puffer, damit Start- und
	  Endartefakte (Fahrzeuge poppen am ersten Link auf, scheinen am letzten
	  Link zurueckzurutschen) nicht auf der Teststrecke sichtbar sind.

	  IDs 100..110 sind Rueckrichtungs-Links, die nur vom MATSim-NetworkCleaner
	  gebraucht werden (das Netz muss stark zusammenhaengend sein). Die Agenten
	  benutzen sie nicht.
	====================================================================== -->

	<nodes>
		<!-- Einfahr-Puffer -->
		<node id="0"  x="-200" y="0" z="0"/>
		<!-- Teststrecke -->
		<node id="1"  x="0"    y="0" z="0"/>
		<node id="2"  x="50"   y="0" z="0"/>
		<node id="3"  x="150"  y="0" z="0"/>
		<node id="4"  x="300"  y="0" z="0"/>
		<node id="5"  x="500"  y="0" z="0"/>
		<node id="6"  x="580"  y="0" z="0"/>
		<node id="7"  x="700"  y="0" z="0"/>
		<node id="8"  x="760"  y="0" z="0"/>
		<node id="9"  x="850"  y="0" z="0"/>
		<node id="10" x="1000" y="0" z="0"/>
		<!-- Ausfahr-Puffer -->
		<node id="11" x="1100" y="0" z="0"/>
	</nodes>

	<links capperiod="01:00:00">

		<!-- Einfahr-Puffer -->
		<link id="0" from="0" to="1" length="200.00" capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>

		<!-- Teststrecke: 9 Links mit variierender Laenge (50..200 m) -->
		<link id="1" from="1" to="2" length="50.00"  capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>
		<link id="2" from="2" to="3" length="100.00" capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>
		<link id="3" from="3" to="4" length="150.00" capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>
		<link id="4" from="4" to="5" length="200.00" capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>
		<link id="5" from="5" to="6" length="80.00"  capacity="5" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>
		<link id="6" from="6" to="7" length="120.00" capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>
		<link id="7" from="7" to="8" length="60.00"  capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>
		<link id="8" from="8" to="9" length="90.00"  capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>
		<link id="9" from="9" to="10" length="150.00" capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>

		<!-- Ausfahr-Puffer -->
		<link id="10" from="10" to="11" length="100.00" capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>

		<!-- Rueckrichtungs-Links (nur fuer NetworkCleaner, werden nicht befahren) -->
		<link id="100" from="1"  to="0"  length="200.00" capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>
		<link id="101" from="2"  to="1"  length="50.00"  capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>
		<link id="102" from="3"  to="2"  length="100.00" capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>
		<link id="103" from="4"  to="3"  length="150.00" capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>
		<link id="104" from="5"  to="4"  length="200.00" capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>
		<link id="105" from="6"  to="5"  length="80.00"  capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>
		<link id="106" from="7"  to="6"  length="120.00" capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>
		<link id="107" from="8"  to="7"  length="60.00"  capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>
		<link id="108" from="9"  to="8"  length="90.00"  capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>
		<link id="109" from="10" to="9"  length="150.00" capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>
		<link id="110" from="11" to="10" length="100.00" capacity="1800" freespeed="13.89" permlanes="2" oneway="1" modes="car,bicycle">
			<attributes><attribute name="type" class="java.lang.String">primary</attribute></attributes>
		</link>

	</links>

</network>

=== matsim-org/matsim-libs/examples/scenarios/ptdisturbances/network.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE network SYSTEM "http://www.matsim.org/files/dtd/network_v2.dtd">
<network>

<!-- ====================================================================== -->

	<nodes>
		<node id="car_0" x="1000.0" y="0.0" >
		</node>
		<node id="car_1" x="0.0" y="2000.0" >
		</node>
		<node id="car_2" x="1000.0" y="2000.0" >
		</node>
		<node id="car_3" x="2000.0" y="2000.0" >
		</node>
		<node id="pt0" x="0.0" y="0.0" >
		</node>
		<node id="pt2" x="2000.0" y="0.0" >
		</node>
		<node id="ptLeftOf3" x="-1000.0" y="900.0" >
		</node>
		<node id="pt3Signal" x="-100.0" y="900.0" >
		</node>
		<node id="carLeftOf3" x="-1000.0" y="1100.0" >
		</node>
		<node id="pt3" x="0.0" y="1000.0" >
		</node>
		<node id="pt4" x="1000.0" y="1000.0" >
		</node>
		<node id="pt5" x="2000.0" y="1000.0" >
		</node>
		<node id="home" x="-100.0" y="0.0" >
		</node>
		<node id="work" x="2100.0" y="1000.0" >
		</node>
	</nodes>

<!-- ====================================================================== -->

	<links capperiod="01:00:00" effectivecellsize="7.5" effectivelanewidth="3.75">
		<link id="car_0" from="pt0" to="pt3" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_1" from="pt0" to="car_0" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_10" from="pt3" to="car_1" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_11" from="pt5" to="pt4" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_12" from="pt5" to="pt2" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_13" from="pt5" to="car_3" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_14" from="car_0" to="pt0" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_15" from="car_0" to="pt4" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_16" from="car_0" to="pt2" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_17" from="car_1" to="pt3" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_17bIn" from="carLeftOf3" to="pt3" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_17bOut" from="pt3" to="carLeftOf3" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_18" from="car_1" to="car_2" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_19" from="car_2" to="pt4" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_2" from="pt4" to="pt3" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_20" from="car_2" to="car_1" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_21" from="car_2" to="car_3" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_22" from="car_3" to="pt5" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_23" from="car_3" to="car_2" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_3" from="pt4" to="pt5" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_4" from="pt4" to="car_0" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_5" from="pt4" to="car_2" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_6" from="pt2" to="pt5" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_7" from="pt2" to="car_0" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_8" from="pt3" to="pt0" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="car_9" from="pt3" to="pt4" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="car" >
		</link>
		<link id="pt0" from="pt0" to="pt0" length="50.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="pt" >
		</link>
		<link id="pt1" from="pt0" to="pt4" length="1414.213562373095" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="pt" >
		</link>
		<link id="pt10" from="pt5" to="pt4" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="pt" >
		</link>
		<link id="pt11" from="pt4" to="pt3" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="pt" >
		</link>
		<link id="pt2" from="pt4" to="pt2" length="1414.213562373095" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="pt" >
		</link>
		<link id="pt3" from="pt2" to="pt2" length="50.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="pt" >
		</link>
		<link id="pt4" from="pt2" to="pt4" length="1414.213562373095" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="pt" >
		</link>
		<link id="pt5" from="pt4" to="pt0" length="1414.213562373095" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="pt" >
		</link>
		<link id="pt6" from="ptLeftOf3" to="ptLeftOf3" length="50.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="pt" >
		</link>
		<link id="pt6b" from="ptLeftOf3" to="pt3Signal" length="800.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="pt" >
		</link>
		<link id="pt6c" from="pt3Signal" to="pt3" length="200.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="pt" >
		</link>
		<link id="pt7" from="pt3" to="pt4" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="pt" >
		</link>
		<link id="pt8" from="pt4" to="pt5" length="1000.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="pt" >
		</link>
		<link id="pt9" from="pt5" to="pt5" length="50.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="pt" >
		</link>
		<link id="home0" from="home" to="pt0" length="100.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="pt, car" >
		</link>
		<link id="home1" from="pt0" to="home" length="100.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="pt, car" >
		</link>
		<link id="work0" from="work" to="pt5" length="100.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="pt, car" >
		</link>
		<link id="work1" from="pt5" to="work" length="100.0" freespeed="8.333333333333334" capacity="500.0" permlanes="1.0" oneway="1" modes="pt, car" >
		</link>
	</links>

<!-- ====================================================================== -->

</network>
