=== matsim-org/matsim-libs/matsim/src/main/resources/dtd/population_v5.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT population     (person)*>
<!ATTLIST population
          desc           CDATA   #IMPLIED>

<!ELEMENT person         (plan*)>
<!ATTLIST person
          id             CDATA                    #REQUIRED
          sex            (f|m)                    #IMPLIED
          age            CDATA                    #IMPLIED
          license        (yes|no)                 #IMPLIED
          car_avail      (always|never|sometimes) #IMPLIED
          employed       (yes|no)                 #IMPLIED>

<!ELEMENT plan           (act|leg)*>
<!ATTLIST plan
          score          CDATA    #IMPLIED
          type           CDATA    #IMPLIED
          selected       (yes|no) "no">

<!ELEMENT act            EMPTY>
<!ATTLIST act
          type           CDATA #REQUIRED
          x              CDATA #IMPLIED
          y              CDATA #IMPLIED
          link           CDATA #IMPLIED
          facility       CDATA #IMPLIED
          start_time     CDATA #IMPLIED
          end_time       CDATA #IMPLIED
          max_dur        CDATA #IMPLIED>

<!ELEMENT leg            (route)?>
<!ATTLIST leg
          mode           CDATA                                                 #REQUIRED
          dep_time       CDATA                                                 #IMPLIED
          trav_time      CDATA                                                 #IMPLIED
          arr_time       CDATA                                                 #IMPLIED>

<!ELEMENT route          (#PCDATA)>
<!ATTLIST route
          type           CDATA #IMPLIED
          start_link	 CDATA #IMPLIED
          end_link       CDATA #IMPLIED
          trav_time		 CDATA #IMPLIED
          distance		 CDATA #IMPLIED
          vehicleRefId           CDATA #IMPLIED
          >

<!-- ============================================================ -->

<!-- ROOT ELEMENT population:
     In here all individuals are stored including their desired
     plan. -->

<!-- ATTRIBUTE desc:
     It is always a good idea to give a plans file a description
     for better identification.
     Normally it should describe, which company / institute / etc..
     created that plans file and / or what has been modified. -->

<!-- ============================================================ -->

<!-- ELEMENT person:
     Each individual is listed here. -->

<!-- ATTRIBUTE id:
     Each person holds a UNIQUE id for identification.
     format := unsigned integer -->
<!-- ATTRIBUTE sex:
     If known, each person has a sex. -->
<!-- ATTRIBUTE age:
     If known, each person has an age.
     format := unsigned integer (inclusive zero) -->
<!-- ATTRIBUTE license:
     Defines if this person holds a drivers-license. -->
<!-- ATTRIBUTE car_avail:
     Defines if this person has access to a car (always, sometimes
     or never). -->
<!-- ATTRIBUTE employed:
     Defines if this person has a job. -->

<!-- ============================================================ -->

<!-- ELEMENT plan:
     Each person holds at least one plan.  A plan holds a sequence of
     act-leg-act-leg... tags.  Such a chain has to start and end with
     an act(ivity).  Between two acts there must be EXACTLY one
     leg. -->

<!-- ATTRIBUTE score:
     Measures the "performance" of this plan based on the outcome of
     the execution of this plan within the simulation (possibly
     several simulations).  After a plan is chosen for a simulation
     and is simulated by the sim, a score will be calculated.  So,
     initial plans don't need to provide a score.  It is just for
     internal use.
     format := double -->

<!-- ATTRIBUTE selected:
     If a person has more than one plan, one is marked as the selected
     plan, i.e., the one to be used by the simulation or other
     modules.  For internal use.  Initial plans do not need to provide
     this. -->

<!-- ============================================================ -->

<!-- ELEMENT act:
     Defines an activity of a person (like working, shopping, etc.).
     An activity is placed on a defined coordinate/link of the given
     network. -->

<!-- ATTRIBUTE type:
     Each activity has to have a type, like w(ork), l(eisure),
     h(ome), s(hopping), e(ducation), etc.
     format := string -->

<!-- ATTRIBUTE x:
     The x coordinate of the activity.
     If x and y is not defined, the link id has to be given!
     format := double
     units  := meter -->

<!-- ATTRIBUTE y:
     The y coordinate of the activity.
     If x and y is not defined, the link id has to be given!
     format := double
     units  := meter -->

<!-- ATTRIBUTE link:
     The id of the link where this activity will be performed.  If
     this attribute is not given, the x and y attributes must be
     defined.
     format := unsigned integer
     unit   := N/A -->

<!-- NOTE: Either (x,y) or link must be defined, otherwise the
           activity cannot be matched on the given network (see
           network_v1.dtd on matsim.org). -->

<!-- ATTRIBUTE facility:
     The id of the facility where this activity will be performed. Optional.
     format := unsigned integer
     unit   := N/A -->

<!-- ATTRIBUTE start_time:
     Defines when an activity should start.
     format := "hh:mm:ss" -->

<!-- ATTRIBUTE end_time:
     Defines when an activity should end.  This is a REQUIRED
     attribute for the FIRST activity, and optional for the other
     ones.
     format := "hh:mm:ss" -->

<!-- ATTRIBUTE max_dur:
     Defines the maximum duration of an activity.
     format := "hh:mm:ss" -->

<!-- ============================================================ -->

<!-- ELEMENT leg:
     Defines one part of the trip between two activities. (I.e. a
     route with the car, a walk by foot, a change of the mode, a time
     where it has to wait for the bus, and so on.)  At the moment,
     MATSim provides only 'car mode' legs. (Oct. 2004) -->

<!-- ATTRIBUTE mode:
     Defines the mode of this leg (e.g. car, bus, foot, bike, etc.).
     format := string -->

<!-- ATTRIBUTE dep_time:
     Expected departure time for this leg.
     This is also for internal use.
     format := "hh:mm:ss" -->

<!-- ATTRIBUTE trav_time:
     Expected travel time for this leg.
     This is also for internal use.
     format := "hh:mm:ss" -->

<!-- ATTRIBUTE arr_time:
     Expected arrival time for this leg.
     This is also for internal use.
     format := "hh:mm:ss" -->

<!-- ============================================================ -->

<!-- ELEMENT route:
     When a leg is a path through a network, it is defined here. -->

<!-- ATTRIBUTE type:
     Defines the kind of route, and in what "format" the route is encoded.
     format := string -->

<!-- ATTRIBUTE trav_time:
     the estimated travel time of the given route
     format := unsigned double -->

<!-- #PCDATA:
     encoding of the route, depending on the type specified -->

<!-- ============================================================ -->

=== matsim-org/matsim-libs/contribs/carsharing/test/input/org/matsim/contrib/carsharing/runExample/RunCarsharingIT/10persons.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE population SYSTEM "http://www.matsim.org/files/dtd/population_v5.dtd">

<population>

<!-- ====================================================================== -->

	<person id="0" employed="yes" >
		<plan selected="yes">
			<act type="h" facility="0" x="0.0" y="-375.0" start_time="00:00:00" max_dur="08:00:00" end_time="08:00:00" />
			<leg mode="car">
			</leg>
			<act type="w" facility="3" x="1000.0" y="-250.0" start_time="08:00:00" max_dur="08:00:00" />
            <leg mode="car">
			</leg>
			<act type="h" facility="0" x="0.0" y="-375.0" start_time="08:00:00" max_dur="08:00:00" />
			<leg mode="car">
			</leg>
			<act type="w" facility="3" x="1000.0" y="-250.0" start_time="08:00:00" max_dur="08:00:00" />
            <leg mode="car">
			</leg>
			<act type="h" facility="0" x="0.0" y="-375.0" start_time="08:00:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="1" employed="yes" >
		<plan selected="yes">
			<act type="h" facility="1" x="-375.0" y="0.0" start_time="00:00:03" max_dur="08:00:00" end_time="08:00:03" />
			<leg mode="car">
			</leg>
			<act type="w" facility="4" x="1250.0" y="0.0" start_time="08:00:03" max_dur="08:00:00" />
            <leg mode="car">
			</leg>
            <act type="h" facility="1" x="-375.0" y="0.0" start_time="08:00:03" max_dur="08:00:00" end_time="16:00:03" />

		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="10" employed="yes">
		<plan selected="yes">
			<act type="h" facility="1" x="-375.0" y="0.0" start_time="00:00:36" max_dur="08:00:00" end_time="08:00:36" />
			<leg mode="car">
			</leg>
			<act type="w" facility="4" x="1250.0" y="0.0" start_time="08:00:36" max_dur="08:00:00" />
            <leg mode="car">
			</leg>
            <act type="h" facility="1" x="-375.0" y="0.0" start_time="08:00:36" max_dur="08:00:00" end_time="16:00:36" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="100" employed="yes">
		<plan selected="yes">
			<act type="h" facility="1" x="-375.0" y="0.0" start_time="00:06:00" max_dur="08:00:00" end_time="08:06:00" />
			<leg mode="car">
			</leg>
			<act type="w" facility="4" x="1250.0" y="0.0" start_time="08:06:00" max_dur="08:00:00" />
            <leg mode="car">
			</leg>
            <act type="h" facility="1" x="-375.0" y="0.0" start_time="08:06:00" max_dur="08:00:00" end_time="16:06:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="101" employed="yes">
		<plan selected="yes">
			<act type="h" facility="2" x="0.0" y="375.0" start_time="00:06:03" max_dur="08:00:00" end_time="08:06:03" />
			<leg mode="car">
			</leg>
			<act type="w" facility="5" x="1000.0" y="250.0" start_time="08:06:03" max_dur="08:00:00" />
            <leg mode="car">
			</leg>
            <act type="h" facility="2" x="0.0" y="375.0" start_time="08:06:03" max_dur="08:00:00" end_time="16:06:03" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="102" employed="yes">
		<plan selected="yes">
			<act type="h" facility="0" x="0.0" y="-375.0" start_time="00:06:07" max_dur="08:00:00" end_time="08:06:07" />
			<leg mode="car">
			</leg>
			<act type="w" facility="3" x="1000.0" y="-250.0" start_time="08:06:07" max_dur="08:00:00" />
            <leg mode="car">
			</leg>
            <act type="h" facility="0" x="0.0" y="-375.0" start_time="08:06:07" max_dur="08:00:00" end_time="16:06:07" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="103" employed="yes">
		<plan selected="yes">
			<act type="h" facility="1" x="-375.0" y="0.0" start_time="00:06:10" max_dur="08:00:00" end_time="08:06:10" />
			<leg mode="car">
			</leg>
			<act type="w" facility="4" x="1250.0" y="0.0" start_time="08:06:10" max_dur="08:00:00" />
            <leg mode="car">
			</leg>
            <act type="h" facility="1" x="-375.0" y="0.0" start_time="08:06:10" max_dur="08:00:00" end_time="16:06:10" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="104" employed="yes">
		<plan selected="yes">
			<act type="h" facility="2" x="0.0" y="375.0" start_time="00:06:14" max_dur="08:00:00" end_time="08:06:14" />
			<leg mode="car">
			</leg>
			<act type="w" facility="5" x="1000.0" y="250.0" start_time="08:06:14" max_dur="08:00:00" />
            <leg mode="car">
			</leg>
            <act type="h" facility="2" x="0.0" y="375.0" start_time="08:06:14" max_dur="08:00:00" end_time="16:06:14" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="105" employed="yes">
		<plan selected="yes">
			<act type="h" facility="0" x="0.0" y="-375.0" start_time="00:06:18" max_dur="08:00:00" end_time="08:06:18" />
			<leg mode="car">
			</leg>
			<act type="w" facility="3" x="1000.0" y="-250.0" start_time="08:06:18" max_dur="08:00:00" />
            <leg mode="car">
			</leg>
            <act type="h" facility="0" x="0.0" y="-375.0" start_time="08:06:18" max_dur="08:00:00" end_time="16:06:18" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="106" employed="yes">
		<plan selected="yes">
			<act type="h" facility="1" x="-375.0" y="0.0" start_time="00:06:21" max_dur="08:00:00" end_time="08:06:21" />
			<leg mode="car">
			</leg>
			<act type="w" facility="4" x="1250.0" y="0.0" start_time="08:06:21" max_dur="08:00:00" />
            <leg mode="car">
			</leg>
            <act type="h" facility="1" x="-375.0" y="0.0" start_time="08:06:21" max_dur="08:00:00" end_time="16:06:21" />
		</plan>

	</person>

<!-- ====================================================================== -->

</population>

=== matsim-org/matsim-libs/matsim/src/test/resources/test/input/org/matsim/core/utils/io/MatsimFileTypeGuesserTest/population_v5_multipleLegsWithRoutes.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE population SYSTEM "http://www.matsim.org/files/dtd/population_v5.dtd">

<population>

	<!-- ====================================================================== -->

	<person id="1" employed="no">
		<plan selected="yes">
			<act type="h" link="1" />
			<leg mode="car">
				<route type="links">1 2</route>
			</leg>
			<leg mode="car">
				<route type="links">2 3 4</route>
			</leg>
			<leg mode="car">
				<route type="links">4 5 6</route>
			</leg>
			<act type="h" link="6" />
		</plan>

	</person>

	<!-- ====================================================================== -->

</population>

=== matsim-org/matsim-libs/contribs/cadytsIntegration/test/input/org/matsim/contrib/cadyts/car/CadytsCarIT/plans5.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE population SYSTEM "http://www.matsim.org/files/dtd/population_v5.dtd">

<population>

<!-- ====================================================================== -->

	<person id="1" employed="no">
		<plan selected="yes">
			<act type="h" link="1" end_time="06:00:00" />
			<leg mode="car">
				<route type="links">1 2 11 20</route>
			</leg>
			<act type="w" link="20" max_dur="00:30:00" />
			<leg mode="car">
				<route type="links">20 21 22 23 1</route>
			</leg>
			<act type="h" link="1" />
		</plan>
		
		<plan selected="no">
			<act type="h" link="1" end_time="06:00:00" />
			<leg mode="car">
				<route type="links">1 10 19 20</route>
			</leg>
			<act type="w" link="20" max_dur="00:30:00" />
			<leg mode="car">
				<route type="links">20 21 22 23 1</route>
			</leg>
			<act type="h" link="1" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="2" employed="no">
		<plan selected="yes">
			<act type="h" link="1" end_time="06:00:00" />
			<leg mode="car">
				<route type="links">1 2 11 20</route>
			</leg>
			<act type="w" link="20" max_dur="00:30:00" />
			<leg mode="car">
				<route type="links">20 21 22 23 1</route>
			</leg>
			<act type="h" link="1" />
		</plan>
		
		<plan selected="no">
			<act type="h" link="1" end_time="06:00:00" />
			<leg mode="car">
				<route type="links">1 10 19 20</route>
			</leg>
			<act type="w" link="20" max_dur="00:30:00" />
			<leg mode="car">
				<route type="links">20 21 22 23 1</route>
			</leg>
			<act type="h" link="1" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="3" employed="no">
		<plan selected="yes">
			<act type="h" link="1" end_time="06:00:00" />
			<leg mode="car">
				<route type="links">1 2 11 20</route>
			</leg>
			<act type="w" link="20" max_dur="00:30:00" />
			<leg mode="car">
				<route type="links">20 21 22 23 1</route>
			</leg>
			<act type="h" link="1" />
		</plan>
		
		<plan selected="no">
			<act type="h" link="1" end_time="06:00:00" />
			<leg mode="car">
				<route type="links">1 10 19 20</route>
			</leg>
			<act type="w" link="20" max_dur="00:30:00" />
			<leg mode="car">
				<route type="links">20 21 22 23 1</route>
			</leg>
			<act type="h" link="1" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="4" employed="no">
		<plan selected="yes">
			<act type="h" link="1" end_time="06:00:00" />
			<leg mode="car">
				<route type="links">1 2 11 20</route>
			</leg>
			<act type="w" link="20" max_dur="00:30:00" />
			<leg mode="car">
				<route type="links">20 21 22 23 1</route>
			</leg>
			<act type="h" link="1" />
		</plan>
		
		<plan selected="no">
			<act type="h" link="1" end_time="06:00:00" />
			<leg mode="car">
				<route type="links">1 10 19 20</route>
			</leg>
			<act type="w" link="20" max_dur="00:30:00" />
			<leg mode="car">
				<route type="links">20 21 22 23 1</route>
			</leg>
			<act type="h" link="1" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="5" employed="no">
		<plan selected="yes">
			<act type="h" link="1" end_time="06:00:00" />
			<leg mode="car">
				<route type="links">1 2 11 20</route>
			</leg>
			<act type="w" link="20" max_dur="00:30:00" />
			<leg mode="car">
				<route type="links">20 21 22 23 1</route>
			</leg>
			<act type="h" link="1" />
		</plan>
		
		<plan selected="no">
			<act type="h" link="1" end_time="06:00:00" />
			<leg mode="car">
				<route type="links">1 10 19 20</route>
			</leg>
			<act type="w" link="20" max_dur="00:30:00" />
			<leg mode="car">
				<route type="links">20 21 22 23 1</route>
			</leg>
			<act type="h" link="1" />
		</plan>

	</person>

<!-- ====================================================================== -->

</population>

=== matsim-org/matsim-libs/contribs/bicycle/src/main/resources/bicycle_example/population_20.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE population SYSTEM "http://www.matsim.org/files/dtd/population_v5.dtd">

<population>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_0">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:00:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:00:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:00:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_1">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:01:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:01:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:01:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_10">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:10:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:10:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:10:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_11">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:11:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:11:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:11:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_12">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:12:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:12:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:12:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_13">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:13:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:13:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:13:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_14">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:14:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:14:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:14:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_15">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:15:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:15:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:15:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_16">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:16:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:16:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:16:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_17">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:17:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:17:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:17:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_18">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:18:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:18:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:18:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_19">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:19:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:19:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:19:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_2">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:02:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:02:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:02:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_3">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:03:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:03:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:03:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_4">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:04:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:04:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:04:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_5">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:05:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:05:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:05:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_6">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:06:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:06:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:06:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_7">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:07:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:07:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:07:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_8">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:08:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:08:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:08:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="bike_home1_work1_9">
		<plan selected="yes">
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:09:00" />
			<leg mode="bike">
			</leg>
			<act type="work" x="4597061.15798372" y="5815895.2771292785" end_time="17:09:00" />
			<leg mode="bike">
			</leg>
			<act type="home" x="4594056.246772228" y="5815823.958524446" end_time="10:09:00" />
		</plan>

	</person>

<!-- ====================================================================== -->

</population>

=== matsim-org/matsim-libs/contribs/decongestion/test/input/org/matsim/contrib/decongestion/population_2agents.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE population SYSTEM "http://www.matsim.org/files/dtd/population_v5.dtd">

<population>

<!-- ====================================================================== -->

	<person id="person_0">
		<plan selected="yes">
			<act type="home" x="0.0" y="0.0" end_time="07:01:00" />
			<leg mode="car">
			</leg>
			<act type="work" x="15000.0" y="0.0" />
		</plan>

	</person>

<!-- ====================================================================== -->

	<person id="person_1">
		<plan selected="yes">
			<act type="home" x="0.0" y="0.0" end_time="07:01:00" />
			<leg mode="car">
			</leg>
			<act type="work" x="15000.0" y="0.0" />
		</plan>

	</person>
	
<!-- ====================================================================== -->

</population>
