=== matsim-org/matsim-libs/matsim/src/main/resources/dtd/signalSystems_v2.0.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.matsim.org/files/dtd" xmlns="http://www.matsim.org/files/dtd"
		elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xml:lang="en">

		<!-- Editor: Dominik Grether, VSP, Berlin Institute of Technology -->
		<!-- Description of the signal systems to be used in the simulation -->

		<xs:include schemaLocation="matsimCommon.xsd" />
		
		<xs:annotation>
				<xs:documentation>Description of the signal systems to be used in the simulation
				</xs:documentation>
				<xs:appinfo xmlns:dc="http://purl.org/dc/elements/1.1/">
						<dc:creator>
								Dominik Grether, VSP, Berlin Institute of Technology
    </dc:creator>
						<dc:title>
								Signal systems for MATSim
    </dc:title>
						<dc:date>
								2010-06-07
    </dc:date>
						<dc:subject>
								matsim, signal system, signal control, transportation, multiagent simulation
						</dc:subject>
						<dc:description>
								Description of the signal systems to be used in the simulation of the MATSim
								framework
    </dc:description>
				</xs:appinfo>
		</xs:annotation>

		<xs:element name="signalSystems">
				<xs:complexType>
						<xs:sequence>
								<xs:element name="signalSystem" type="signalSystemType"
										minOccurs="0" maxOccurs="unbounded" />
						</xs:sequence>
				</xs:complexType>
		</xs:element>

		<xs:complexType name="signalSystemType">
				<xs:complexContent>
						<xs:extension base="matsimObjectType">
								<xs:sequence>
										<xs:element name="signals" minOccurs="1" maxOccurs="1">
												<xs:complexType>
														<xs:sequence>
																<xs:element name="signal" type="signalType"
																		minOccurs="1" maxOccurs="unbounded" />
														</xs:sequence>
												</xs:complexType>
										</xs:element>
								</xs:sequence>
						</xs:extension>
				</xs:complexContent>
		</xs:complexType>

		<xs:complexType name="signalType">
				<xs:complexContent>
						<xs:extension base="matsimObjectType">
								<xs:sequence>
										<xs:element name="lane" minOccurs="0" maxOccurs="unbounded">
												<xs:annotation>
														<xs:documentation>
                            </xs:documentation>
												</xs:annotation>
												<xs:complexType>
														<xs:complexContent>
																<xs:extension base="idRefType" />
														</xs:complexContent>
												</xs:complexType>
										</xs:element>
										
										<xs:element name="turningMoveRestrictions" minOccurs="0" maxOccurs="1">
												<xs:annotation>
														<xs:documentation>
														</xs:documentation>
												</xs:annotation>
												<xs:complexType>
														<xs:sequence>
																<xs:element name="toLink" type="idRefType" minOccurs="0" maxOccurs="unbounded"/>
														</xs:sequence>
												</xs:complexType>
										</xs:element>
								</xs:sequence>
								<xs:attribute name="linkIdRef" type="matsimIdType" use="required"></xs:attribute>
						</xs:extension>
				</xs:complexContent>
		</xs:complexType>
</xs:schema>

=== matsim-org/matsim-libs/playgrounds/tthunig/test/input/scenarios/cottbus/FixCottbusResultsIT/btuOpt/signal_systems_no_13_btuNet.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<signalSystems xsi:schemaLocation="http://www.matsim.org/files/dtd http://www.matsim.org/files/dtd/signalSystems_v2.0.xsd" xmlns="http://www.matsim.org/files/dtd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <signalSystem id="23">
        <signals>
            <signal linkIdRef="2759" id="2603">
                <lane refId="2603"/>
            </signal>
            <signal linkIdRef="2759" id="2602">
                <lane refId="2602"/>
            </signal>
            <signal linkIdRef="6708" id="2612">
                <lane refId="2612"/>
            </signal>
            <signal linkIdRef="2759" id="2601">
                <lane refId="2601"/>
            </signal>
            <signal linkIdRef="6708" id="2611">
                <lane refId="2611"/>
            </signal>
            <signal linkIdRef="6708" id="2610">
                <lane refId="2610"/>
            </signal>
            <signal linkIdRef="6713-6711" id="2609">
                <lane refId="2609"/>
            </signal>
            <signal linkIdRef="6713-6711" id="2608">
                <lane refId="2608"/>
            </signal>
            <signal linkIdRef="6713-6711" id="2607">
                <lane refId="2607"/>
            </signal>
            <signal linkIdRef="589-587-585-583" id="2606">
                <lane refId="2606"/>
            </signal>
            <signal linkIdRef="589-587-585-583" id="2605">
                <lane refId="2605"/>
            </signal>
            <signal linkIdRef="589-587-585-583" id="2604">
                <lane refId="2604"/>
            </signal>
        </signals>
    </signalSystem>
    <signalSystem id="12">
        <signals>
            <signal linkIdRef="8212-8213" id="1404">
                <lane refId="1404"/>
            </signal>
            <signal linkIdRef="1450-1451" id="1403">
                <lane refId="1403"/>
            </signal>
            <signal linkIdRef="1450-1451" id="1402">
                <lane refId="1402"/>
            </signal>
            <signal linkIdRef="1281" id="1412">
                <lane refId="1412"/>
            </signal>
            <signal linkIdRef="1450-1451" id="1401">
                <lane refId="1401"/>
            </signal>
            <signal linkIdRef="1281" id="1411">
                <lane refId="1411"/>
            </signal>
            <signal linkIdRef="1281" id="1410">
                <lane refId="1410"/>
            </signal>
            <signal linkIdRef="9651-9659-9657-9655-9653" id="1409">
                <lane refId="1409"/>
            </signal>
            <signal linkIdRef="9651-9659-9657-9655-9653" id="1408">
                <lane refId="1408"/>
            </signal>
            <signal linkIdRef="9651-9659-9657-9655-9653" id="1407">
                <lane refId="1407"/>
            </signal>
            <signal linkIdRef="8212-8213" id="1406">
                <lane refId="1406"/>
            </signal>
            <signal linkIdRef="8212-8213" id="1405">
                <lane refId="1405"/>
            </signal>
        </signals>
    </signalSystem>
    <signalSystem id="24">
        <signals>
            <signal linkIdRef="1685" id="2713"/>
            <signal linkIdRef="582-584-586-588" id="2701"/>
            <signal linkIdRef="567-565-563-561" id="2710"/>
            <signal linkIdRef="1680" id="2707"/>
            <signal linkIdRef="4587" id="2704"/>
        </signals>
    </signalSystem>
    <signalSystem id="25">
        <signals>
            <signal linkIdRef="1760" id="2801"/>
            <signal linkIdRef="140-138" id="2810"/>
            <signal linkIdRef="4586" id="2807"/>
            <signal linkIdRef="9644-9646-9648" id="2804"/>
        </signals>
    </signalSystem>
    <signalSystem id="14">
        <signals>
            <signal linkIdRef="5157-5155-5153" id="1107">
                <lane refId="1107"/>
            </signal>
            <signal linkIdRef="9346-9347" id="1106">
                <lane refId="1106"/>
            </signal>
            <signal linkIdRef="9346-9347" id="1105">
                <lane refId="1105"/>
            </signal>
            <signal linkIdRef="9346-9347" id="1104">
                <lane refId="1104"/>
            </signal>
            <signal linkIdRef="2475" id="1103">
                <lane refId="1103"/>
            </signal>
            <signal linkIdRef="2475" id="1102">
                <lane refId="1102"/>
            </signal>
            <signal linkIdRef="7919" id="1112">
                <lane refId="1112"/>
            </signal>
            <signal linkIdRef="2475" id="1101">
                <lane refId="1101"/>
            </signal>
            <signal linkIdRef="7919" id="1111">
                <lane refId="1111"/>
            </signal>
            <signal linkIdRef="7919" id="1110">
                <lane refId="1110"/>
            </signal>
            <signal linkIdRef="5157-5155-5153" id="1109">
                <lane refId="1109"/>
            </signal>
            <signal linkIdRef="5157-5155-5153" id="1108">
                <lane refId="1108"/>
            </signal>
        </signals>
    </signalSystem>
    <signalSystem id="26">
        <signals>
            <signal linkIdRef="137-139" id="2911">
                <lane refId="2911"/>
            </signal>
            <signal linkIdRef="137-139" id="2910">
                <lane refId="2910"/>
            </signal>
            <signal linkIdRef="5744" id="2907"/>
            <signal linkIdRef="8745-8747-10284" id="2905">
                <lane refId="2905"/>
            </signal>
            <signal linkIdRef="8745-8747-10284" id="2904">
                <lane refId="2904"/>
            </signal>
            <signal linkIdRef="1777" id="2902">
                <lane refId="2902"/>
            </signal>
            <signal linkIdRef="1777" id="2901">
                <lane refId="2901"/>
            </signal>
        </signals>
    </signalSystem>
    <signalSystem id="27">
        <signals>
            <signal linkIdRef="7427" id="3008">
                <lane refId="3008"/>
            </signal>
            <signal linkIdRef="7427" id="3007">
                <lane refId="3007"/>
            </signal>
            <signal linkIdRef="7414" id="3004"/>
            <signal linkIdRef="295" id="3003">
                <lane refId="3003"/>
            </signal>
            <signal linkIdRef="295" id="3001">
                <lane refId="3001"/>
            </signal>
            <signal linkIdRef="7300" id="3010"/>
        </signals>
    </signalSystem>
    <signalSystem id="16">
        <signals>
            <signal linkIdRef="8214-9345" id="1204">
                <lane refId="1204"/>
            </signal>
            <signal linkIdRef="1448-1449" id="1201">
                <lane refId="1201"/>
            </signal>
            <signal linkIdRef="4909" id="1210"/>
            <signal linkIdRef="3022-3024-3026" id="1207"/>
        </signals>
    </signalSystem>
    <signalSystem id="17">
        <signals>
            <signal linkIdRef="40" id="2108">
                <lane refId="2108"/>
            </signal>
            <signal linkIdRef="40" id="2107">
                <lane refId="2107"/>
            </signal>
            <signal linkIdRef="6216" id="2106">
                <lane refId="2106"/>
            </signal>
            <signal linkIdRef="6216" id="2105">
                <lane refId="2105"/>
            </signal>
            <signal linkIdRef="6216" id="2104">
                <lane refId="2104"/>
            </signal>
            <signal linkIdRef="3503" id="2103">
                <lane refId="2103"/>
            </signal>
            <signal linkIdRef="3503" id="2102">
                <lane refId="2102"/>
            </signal>
            <signal linkIdRef="9994-9991-9969" id="2112">
                <lane refId="2112"/>
            </signal>
            <signal linkIdRef="3503" id="2101">
                <lane refId="2101"/>
            </signal>
            <signal linkIdRef="9994-9991-9969" id="2111">
                <lane refId="2111"/>
            </signal>
            <signal linkIdRef="9994-9991-9969" id="2110">
                <lane refId="2110"/>
            </signal>
            <signal linkIdRef="40" id="2109">
                <lane refId="2109"/>
            </signal>
        </signals>
    </signalSystem>
    <signalSystem id="28">
        <signals>
            <signal linkIdRef="313-9755-9757-9759-9761" id="3208">
                <lane refId="3208"/>
            </signal>
            <signal linkIdRef="313-9755-9757-9759-9761" id="3207">
                <lane refId="3207"/>
            </signal>
            <signal linkIdRef="1501-1503" id="3206">
                <lane refId="3206"/>
            </signal>
            <signal linkIdRef="1501-1503" id="3205">
                <lane refId="3205"/>
            </signal>
            <signal linkIdRef="1501-1503" id="3204">
                <lane refId="3204"/>
            </signal>
            <signal linkIdRef="6780-6778-6776-2513-2515" id="3203">
                <lane refId="3203"/>
            </signal>
            <signal linkIdRef="6780-6778-6776-2513-2515" id="3202">
                <lane refId="3202"/>
            </signal>
            <signal linkIdRef="6780-6778-6776-2513-2515" id="3201">
                <lane refId="3201"/>
            </signal>
            <signal linkIdRef="7428" id="3212">
                <lane refId="3212"/>
            </signal>
            <signal linkIdRef="7428" id="3211">
                <lane refId="3211"/>
            </signal>
            <signal linkIdRef="7428" id="3210">
                <lane refId="3210"/>
            </signal>
            <signal linkIdRef="313-9755-9757-9759-9761" id="3209">
                <lane refId="3209"/>
            </signal>
        </signals>
    </signalSystem>
    <signalSystem id="18">
        <signals>
