=== matsim-org/matsim-libs/matsim/src/main/resources/dtd/signalGroups_v2.0.xsd
<xs:schema targetNamespace="http://www.matsim.org/files/dtd" xmlns="http://www.matsim.org/files/dtd"
		elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xml:lang="en">

		<!-- Editor: Dominik Grether, VSP, Berlin Institute of Technology -->
		<!-- Definition of the grouping of single signals -->

		<xs:include schemaLocation="matsimCommon.xsd" />

		<xs:element name="signalGroups">
				<xs:complexType>
						<xs:sequence>
								<xs:element name="signalSystem" type="signalSystemSignalGroupType"
										minOccurs="0" maxOccurs="unbounded" />
						</xs:sequence>
				</xs:complexType>
		</xs:element>

	<xs:complexType name="signalSystemSignalGroupType">
		<xs:complexContent>
			<xs:extension base="idRefType">
				<xs:sequence>
					<xs:element name="signalGroup" type="signalGroupType" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

		<xs:complexType name="signalGroupType">
				<xs:complexContent>
						<xs:extension base="matsimObjectType">
								<xs:sequence>
										<xs:element name="signal" type="idRefType" minOccurs="1" maxOccurs="unbounded" />
								</xs:sequence>
						</xs:extension>
				</xs:complexContent>
		</xs:complexType>
</xs:schema>

=== matsim-org/matsim-libs/contribs/signals/examples/tutorial/example90TrafficLights/useSignalInput/withLanes/signal_groups.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<signalGroups xsi:schemaLocation="http://www.matsim.org/files/dtd http://www.matsim.org/files/dtd/signalGroups_v2.0.xsd" xmlns="http://www.matsim.org/files/dtd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <signalSystem refId="2">
        <signalGroup id="1">
            <signal refId="1"/>
        </signalGroup>
        <signalGroup id="2">
            <signal refId="2"/>
        </signalGroup>
        <signalGroup id="3">
            <signal refId="3"/>
        </signalGroup>
        <signalGroup id="4">
            <signal refId="4"/>
        </signalGroup>
    </signalSystem>
    <signalSystem refId="5">
        <signalGroup id="1">
            <signal refId="1"/>
        </signalGroup>
        <signalGroup id="2">
            <signal refId="2"/>
        </signalGroup>
        <signalGroup id="3">
            <signal refId="3"/>
        </signalGroup>
        <signalGroup id="4">
            <signal refId="4"/>
        </signalGroup>
    </signalSystem>
</signalGroups>
