=== matsim-org/matsim-libs/matsim/src/main/resources/dtd/transitSchedule_v2.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT transitSchedule  (attributes?,transitStops?,minimalTransferTimes?,transitLine*)>


<!ELEMENT attributes    (attribute*)>

<!ELEMENT attribute       (#PCDATA)>
<!ATTLIST attribute
          name             CDATA #REQUIRED
          class            CDATA #REQUIRED>

<!ELEMENT transitStops     (stopFacility)*>

<!ELEMENT stopFacility     (attributes?)>
<!ATTLIST stopFacility
          id               CDATA   #REQUIRED
          x                CDATA   #REQUIRED
          y                CDATA   #REQUIRED
          z                CDATA   #IMPLIED
          linkRefId        CDATA   #IMPLIED
          name             CDATA   #IMPLIED
          stopAreaId       CDATA   #IMPLIED
          isBlocking       (true|false)  "false">

<!ELEMENT minimalTransferTimes    (relation*)>

<!ELEMENT relation         EMPTY>
<!ATTLIST relation
          fromStop         CDATA   #REQUIRED
          toStop           CDATA   #REQUIRED
          transferTime     CDATA   #REQUIRED>
<!-- relations specify the transferTime in seconds between two stop facilities in the specified direction -->

<!ELEMENT transitLine      (attributes?,transitRoute*)>
<!ATTLIST transitLine
          id               CDATA   #REQUIRED
          name             CDATA   #IMPLIED>

<!ELEMENT transitRoute     (attributes?,description?,transportMode,routeProfile,route?,departures)>
<!ATTLIST transitRoute
          id               CDATA   #REQUIRED>
<!-- transitRoute.id must be unique within a transitLine only. -->

<!ELEMENT description      (#PCDATA)>

<!ELEMENT transportMode    (#PCDATA)>
<!-- describes the mode of which vehicles are that serve that line/route -->

<!ELEMENT routeProfile     (stop)*>

<!ELEMENT stop             EMPTY>
<!ATTLIST stop
          refId            CDATA   #REQUIRED
          departureOffset  CDATA   #IMPLIED
          arrivalOffset    CDATA   #IMPLIED
          awaitDeparture   (true|false)  "false">
<!--
 * stop.departureOffset is required for all stops but the last.
   The offsets are to be added to the departure times of the single
   departures listed in the transitRoute.
 * stop.refId are id-references to facilities. -->

<!ELEMENT route            (link)*>

<!ELEMENT link             EMPTY>
<!ATTLIST link
          refId            CDATA   #REQUIRED>

<!ELEMENT departures       (departure*)>
<!-- the single departures along that transitRoute -->

<!ELEMENT departure        (attributes?)>
<!ATTLIST departure
          id               CDATA   #REQUIRED
          departureTime    CDATA   #REQUIRED
          vehicleRefId     CDATA   #IMPLIED>
<!-- the departure.id must be unique within a transitLine only -->

=== matsim-org/matsim-libs/contribs/railsim/test/input/ch/sbb/matsim/contrib/railsim/integration/mesoUniDirectionalVaryingCapacities/transitSchedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE transitSchedule SYSTEM "http://www.matsim.org/files/dtd/transitSchedule_v2.dtd">

<transitSchedule>

	<transitStops>
		<stopFacility id="t1" x="0.0" y="-10000" linkRefId="t1_IN-t1_OUT" isBlocking="false">
		</stopFacility>
		<stopFacility id="t2" x="50000.0" y="-10000" linkRefId="t2_IN-t2_OUT" isBlocking="false">
		</stopFacility>
		<stopFacility id="t3" x="120000.0" y="-10000" linkRefId="t3_IN-t3_OUT" isBlocking="false">
		</stopFacility>
	</transitStops>
	<transitLine id="line1">
		<transitRoute id="line1_route1_0">
			<transportMode>rail</transportMode>
			<routeProfile>
				<stop refId="t1" departureOffset="00:00:00" awaitDeparture="false"/>
				<stop refId="t2" arrivalOffset="02:00:00" departureOffset="02:30:00" awaitDeparture="false"/>
				<stop refId="t3" arrivalOffset="04:00:00" awaitDeparture="false"/>
			</routeProfile>
			<route>
				<link refId="t1_IN-t1_OUT"/>
				<link refId="t1_OUT-t2_IN"/>
				<link refId="t2_IN-t2_OUT"/>
				<link refId="t2_OUT-t3_IN"/>
				<link refId="t3_IN-t3_OUT"/>
			</route>
			<departures>
				<departure id="0" departureTime="08:00:00" vehicleRefId="train1"/>
				<departure id="1" departureTime="08:01:00" vehicleRefId="train2"/>
				<departure id="2" departureTime="08:02:00" vehicleRefId="train3"/>
				<departure id="3" departureTime="08:03:00" vehicleRefId="train4"/>
				<departure id="4" departureTime="08:04:00" vehicleRefId="train5"/>
				<departure id="5" departureTime="08:05:00" vehicleRefId="train6"/>
				<departure id="6" departureTime="08:06:00" vehicleRefId="train7"/>
				<departure id="7" departureTime="08:07:00" vehicleRefId="train8"/>
				<departure id="8" departureTime="08:08:00" vehicleRefId="train9"/>
				<departure id="9" departureTime="08:09:00" vehicleRefId="train10"/>


			</departures>
		</transitRoute>
	</transitLine>
</transitSchedule>

=== matsim-org/matsim-libs/contribs/railsim/test/input/ch/sbb/matsim/contrib/railsim/integration/microTrainFollowingFixedVsMovingBlock/transitSchedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE transitSchedule SYSTEM "http://www.matsim.org/files/dtd/transitSchedule_v2.dtd">

<transitSchedule>

	<transitStops>
		<stopFacility id="t1_1-t1_2" x="100" y="0" linkRefId="t1_1-t1_2">
		</stopFacility>
		<stopFacility id="t1_40-t1_41" x="4900" y="0" linkRefId="t1_40-t1_41">
		</stopFacility>
		<stopFacility id="t2_1-t2_2" x="100" y="-200" linkRefId="t2_1-t2_2">
		</stopFacility>
		<stopFacility id="t2_6-t2_7" x="4900" y="-200" linkRefId="t2_6-t2_7">
		</stopFacility>
	</transitStops>
	<transitLine id="t1_line">
		<transitRoute id="t1_line_route">
			<transportMode>rail</transportMode>
			<routeProfile>
				<stop refId="t1_1-t1_2" departureOffset="00:00:00" awaitDeparture="true"/>
				<stop refId="t1_40-t1_41" arrivalOffset="01:00:00" awaitDeparture="true"/>
			</routeProfile>
			<route>
				<link refId="t1_1-t1_2"/>
				<link refId="t1_2-t1_3"/>
				<link refId="t1_3-t1_4"/>
				<link refId="t1_4-t1_5"/>
				<link refId="t1_5-t1_6"/>
				<link refId="t1_6-t1_7"/>
				<link refId="t1_7-t1_8"/>
				<link refId="t1_8-t1_9"/>
				<link refId="t1_9-t1_10"/>
				<link refId="t1_10-t1_11"/>
				<link refId="t1_11-t1_12"/>
				<link refId="t1_12-t1_13"/>
				<link refId="t1_13-t1_14"/>
				<link refId="t1_14-t1_15"/>
				<link refId="t1_15-t1_16"/>
				<link refId="t1_16-t1_17"/>
				<link refId="t1_17-t1_18"/>
				<link refId="t1_18-t1_19"/>
				<link refId="t1_19-t1_20"/>
				<link refId="t1_20-t1_21"/>
				<link refId="t1_21-t1_22"/>
				<link refId="t1_22-t1_23"/>
				<link refId="t1_23-t1_24"/>
				<link refId="t1_24-t1_25"/>
				<link refId="t1_25-t1_26"/>
				<link refId="t1_26-t1_27"/>
				<link refId="t1_27-t1_28"/>
				<link refId="t1_28-t1_29"/>
				<link refId="t1_29-t1_30"/>
				<link refId="t1_30-t1_31"/>
				<link refId="t1_31-t1_32"/>
				<link refId="t1_32-t1_33"/>
				<link refId="t1_33-t1_34"/>
				<link refId="t1_34-t1_35"/>
				<link refId="t1_35-t1_36"/>
				<link refId="t1_36-t1_37"/>
				<link refId="t1_37-t1_38"/>
				<link refId="t1_38-t1_39"/>
				<link refId="t1_39-t1_40"/>
				<link refId="t1_40-t1_41"/>
			</route>
			<departures>
				<departure id="t1_0" departureTime="08:00:00" vehicleRefId="t1_train1"/>
				<departure id="t1_1" departureTime="08:00:05" vehicleRefId="t1_train2"/>
			</departures>
		</transitRoute>
	</transitLine>
	<transitLine id="t2_line">
		<transitRoute id="t2_line_route">
			<transportMode>rail</transportMode>
			<routeProfile>
				<stop refId="t2_1-t2_2" departureOffset="00:00:00" awaitDeparture="true"/>
				<stop refId="t2_6-t2_7" arrivalOffset="01:00:00" awaitDeparture="true"/>
			</routeProfile>
			<route>
				<link refId="t2_1-t2_2"/>
				<link refId="t2_2-t2_3"/>
				<link refId="t2_3-t2_4"/>
				<link refId="t2_4-t2_5"/>
				<link refId="t2_5-t2_6"/>
				<link refId="t2_6-t2_7"/>
			</route>
			<departures>
				<departure id="t2_0" departureTime="08:00:00" vehicleRefId="t2_train1"/>
				<departure id="t2_1" departureTime="08:00:05" vehicleRefId="t2_train2"/>
			</departures>
		</transitRoute>
	</transitLine>
</transitSchedule>

=== matsim-org/matsim-libs/contribs/railsim/test/input/ch/sbb/matsim/contrib/railsim/integration/microStationReroutingTwoDirections/transitSchedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE transitSchedule SYSTEM "http://www.matsim.org/files/dtd/transitSchedule_v2.dtd">
<transitSchedule>
    <transitStops>
		<stopFacility id="b_oben_start" x="0" y="710" linkRefId="0b_1b" stopAreaId="b_links"/>
		<stopFacility id="b_oben_end" x="11000" y="710" linkRefId="6b_17b" stopAreaId="b_rechts"/>

        <stopFacility id="b_unten_start" x="10000" y="700" linkRefId="15b_14b" stopAreaId="b_rechts"/>
        <stopFacility id="b_unten_end" x="-1000" y="700" linkRefId="11b_16b" stopAreaId="b_links"/>
		
		<!-- links nach rechts -->
		<stopFacility id="9b_10b" x="5000" y="705" linkRefId="9b_10b" stopAreaId="b_mitte"/>
		<stopFacility id="7b_8b" x="5000" y="705" linkRefId="7b_8b" stopAreaId="b_mitte"/>
		<stopFacility id="3b_4b" x="5000" y="705" linkRefId="3b_4b" stopAreaId="b_mitte"/>
		<!-- rechts nach links -->
		<stopFacility id="10b_9b" x="5000" y="705" linkRefId="10b_9b" stopAreaId="b_mitte"/>
		<stopFacility id="8b_7b" x="5000" y="705" linkRefId="8b_7b" stopAreaId="b_mitte"/>
		<stopFacility id="13b_12b" x="5000" y="705" linkRefId="13b_12b" stopAreaId="b_mitte"/>

    </transitStops>
	
    <transitLine id="B1">
            <transitRoute id="B1_oben_IC">
				<transportMode>rail</transportMode>
				<routeProfile>
					<stop refId="b_oben_start" departureOffset="00:00:00" awaitDeparture="true"/>
					<stop refId="b_oben_end" arrivalOffset="00:20:00" awaitDeparture="true"/>
				</routeProfile>	
                <route>
                    <link refId="0b_1b"/>
					<link refId="1b_1b_1"/>
					<link refId="1b_1_1b_2"/>
					<link refId="1b_2_1b_3"/>
					<link refId="1b_3_1b_4"/>
					<link refId="1b_4_1b_5"/>
					<link refId="1b_5_1b_6"/>
					<link refId="1b_6_1b_7"/>
					<link refId="1b_7_1b_8"/>
                    <link refId="1b_8_2b"/>
                    <link refId="2b_3b"/>
					<link refId="3b_4b"/>
					<link refId="4b_5b"/>
					<link refId="5b_5b_1"/>
					<link refId="5b_1_5b_2"/>
					<link refId="5b_2_5b_3"/>
					<link refId="5b_3_5b_4"/>
					<link refId="5b_4_5b_5"/>
					<link refId="5b_5_5b_6"/>
					<link refId="5b_6_5b_7"/>
					<link refId="5b_7_5b_8"/>
					<link refId="5b_8_6b"/>
                    <link refId="6b_17b"/>
					
					<!-- 
					
					<link refId="0b_1b"/>
					<link refId="1b_1b_1"/>
					<link refId="1b_1_1b_2"/>
					<link refId="1b_2_1b_3"/>
					<link refId="1b_3_1b_4"/>
					<link refId="1b_4_1b_5"/>
					<link refId="1b_5_1b_6"/>
					<link refId="1b_6_1b_7"/>
					<link refId="1b_7_1b_8"/>
                    <link refId="1b_8_2b"/>
                    <link refId="2b_3b"/>
					<link refId="3b_7b"/>
					<link refId="7b_8b"/>
					<link refId="8b_4b"/>
					<link refId="4b_5b"/>
					<link refId="5b_5b_1"/>
					<link refId="5b_1_5b_2"/>
					<link refId="5b_2_5b_3"/>
					<link refId="5b_3_5b_4"/>
					<link refId="5b_4_5b_5"/>
					<link refId="5b_5_5b_6"/>
					<link refId="5b_6_5b_7"/>
					<link refId="5b_7_5b_8"/>
					<link refId="5b_8_6b"/>
                    <link refId="6b_17b"/>
					
					-->
					
                </route>
                <departures>
					<departure id="0" departureTime="08:05:00" vehicleRefId="IC_BO_0"/>
					<departure id="1" departureTime="08:20:00" vehicleRefId="IC_BO_1"/>
					<departure id="2" departureTime="08:35:00" vehicleRefId="IC_BO_2"/>
					<departure id="3" departureTime="08:50:00" vehicleRefId="IC_BO_3"/>
				</departures>
            </transitRoute>
			 <transitRoute id="B1_oben_RE">
				<transportMode>rail</transportMode>
				<routeProfile>
					<stop refId="b_oben_start" departureOffset="00:00:00" awaitDeparture="true"/>
					<stop refId="7b_8b" arrivalOffset="00:07:00" departureOffset="00:10:00" awaitDeparture="true"/>
					<stop refId="b_oben_end" arrivalOffset="00:17:00" awaitDeparture="true"/>
				</routeProfile>	
                <route>
                    <link refId="0b_1b"/>
					<link refId="1b_1b_1"/>
					<link refId="1b_1_1b_2"/>
					<link refId="1b_2_1b_3"/>
					<link refId="1b_3_1b_4"/>
					<link refId="1b_4_1b_5"/>
					<link refId="1b_5_1b_6"/>
					<link refId="1b_6_1b_7"/>
					<link refId="1b_7_1b_8"/>
                    <link refId="1b_8_2b"/>
                    <link refId="2b_3b"/>
					<link refId="3b_7b"/>
					<link refId="7b_8b"/>
					<link refId="8b_4b"/>
					<link refId="4b_5b"/>
					<link refId="5b_5b_1"/>
					<link refId="5b_1_5b_2"/>
					<link refId="5b_2_5b_3"/>
					<link refId="5b_3_5b_4"/>
					<link refId="5b_4_5b_5"/>
					<link refId="5b_5_5b_6"/>
					<link refId="5b_6_5b_7"/>
					<link refId="5b_7_5b_8"/>
					<link refId="5b_8_6b"/>
                    <link refId="6b_17b"/>
                </route>
                <departures>
					<departure id="0" departureTime="08:00:00" vehicleRefId="RE_BO_0"/>
					<departure id="1" departureTime="08:15:00" vehicleRefId="RE_BO_1"/>
					<departure id="2" departureTime="08:30:00" vehicleRefId="RE_BO_2"/>
					<departure id="3" departureTime="08:45:00" vehicleRefId="RE_BO_3"/>
				</departures>
            </transitRoute>
			<transitRoute id="B1_unten_IC">
				<transportMode>rail</transportMode>
				<routeProfile>
					<stop refId="b_unten_start" departureOffset="00:00:00" awaitDeparture="true"/>
					<stop refId="b_unten_end" arrivalOffset="00:20:00" awaitDeparture="true"/>
				</routeProfile>	
                <route>
                    <link refId="15b_14b"/>
					<link refId="14b_14b_1"/>
					<link refId="14b_1_14b_2"/>
					<link refId="14b_2_14b_3"/>
					<link refId="14b_3_14b_4"/>
					<link refId="14b_4_14b_5"/>
					<link refId="14b_5_14b_6"/>
					<link refId="14b_6_14b_7"/>
					<link refId="14b_7_14b_8"/>
					<link refId="14b_8_13b"/>
                    <link refId="13b_12b"/>
					<link refId="12b_12b_1"/>
					<link refId="12b_1_12b_2"/>
					<link refId="12b_2_12b_3"/>
					<link refId="12b_3_12b_4"/>
					<link refId="12b_4_12b_5"/>
					<link refId="12b_5_12b_6"/>
					<link refId="12b_6_12b_7"/>
					<link refId="12b_7_12b_8"/>
					<link refId="12b_8_11b"/>
                    <link refId="11b_16b"/>
					
					<!-- 
					
					<link refId="15b_14b"/>
					<link refId="14b_14b_1"/>
					<link refId="14b_1_14b_2"/>
					<link refId="14b_2_14b_3"/>
					<link refId="14b_3_14b_4"/>
					<link refId="14b_4_14b_5"/>
					<link refId="14b_5_14b_6"/>
					<link refId="14b_6_14b_7"/>
					<link refId="14b_7_14b_8"/>
					<link refId="14b_8_13b"/>
                    <link refId="13b_5b"/>
					<link refId="5b_4b"/>
					<link refId="4b_8b"/>
					<link refId="8b_10b"/>
					<link refId="10b_9b"/>
					<link refId="9b_7b"/>
					<link refId="7b_3b"/>
					<link refId="3b_2b"/>
					<link refId="2b_12b"/>
					<link refId="12b_12b_1"/>
					<link refId="12b_1_12b_2"/>
					<link refId="12b_2_12b_3"/>
					<link refId="12b_3_12b_4"/>
					<link refId="12b_4_12b_5"/>
					<link refId="12b_5_12b_6"/>
					<link refId="12b_6_12b_7"/>
					<link refId="12b_7_12b_8"/>
					<link refId="12b_8_11b"/>
                    <link refId="11b_16b"/>
					
					-->
					
                </route>
                <departures>
					<departure id="0" departureTime="08:05:00" vehicleRefId="IC_BU_0"/>
					<departure id="1" departureTime="08:20:00" vehicleRefId="IC_BU_1"/>
					<departure id="2" departureTime="08:35:00" vehicleRefId="IC_BU_2"/>
					<departure id="3" departureTime="08:50:00" vehicleRefId="IC_BU_3"/>
				</departures>
            </transitRoute>
			 <transitRoute id="B1_unten_RE">
				<transportMode>rail</transportMode>
				<routeProfile>
					<stop refId="b_unten_start" departureOffset="00:00:00" awaitDeparture="true"/>
					<stop refId="10b_9b" arrivalOffset="00:07:00" departureOffset="00:10:00" awaitDeparture="true"/>
					<stop refId="b_unten_end" arrivalOffset="00:17:00" awaitDeparture="true"/>
				</routeProfile>	
				<route>
					<link refId="15b_14b"/>
					<link refId="14b_14b_1"/>
					<link refId="14b_1_14b_2"/>
					<link refId="14b_2_14b_3"/>
					<link refId="14b_3_14b_4"/>
					<link refId="14b_4_14b_5"/>
					<link refId="14b_5_14b_6"/>
					<link refId="14b_6_14b_7"/>
					<link refId="14b_7_14b_8"/>
					<link refId="14b_8_13b"/>
                    <link refId="13b_5b"/>
					<link refId="5b_4b"/>
					<link refId="4b_8b"/>
					<link refId="8b_10b"/>
					<link refId="10b_9b"/>
					<link refId="9b_7b"/>
					<link refId="7b_3b"/>
					<link refId="3b_2b"/>
					<link refId="2b_12b"/>
					<link refId="12b_12b_1"/>
					<link refId="12b_1_12b_2"/>
					<link refId="12b_2_12b_3"/>
					<link refId="12b_3_12b_4"/>
					<link refId="12b_4_12b_5"/>
					<link refId="12b_5_12b_6"/>
					<link refId="12b_6_12b_7"/>
					<link refId="12b_7_12b_8"/>
					<link refId="12b_8_11b"/>
                    <link refId="11b_16b"/>
				</route>
                <departures>
					<departure id="0" departureTime="07:50:00" vehicleRefId="RE_BU_0"/>
					<departure id="1" departureTime="08:05:00" vehicleRefId="RE_BU_1"/>
					<departure id="2" departureTime="08:20:00" vehicleRefId="RE_BU_2"/>
					<departure id="3" departureTime="08:35:00" vehicleRefId="RE_BU_3"/>
				</departures>
            </transitRoute>
        </transitLine>
		
</transitSchedule>

=== matsim-org/matsim-libs/contribs/railsim/test/input/ch/sbb/matsim/contrib/railsim/integration/microThreeUniDirectionalTracks/transitSchedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE transitSchedule SYSTEM "http://www.matsim.org/files/dtd/transitSchedule_v2.dtd">

<transitSchedule>

	<transitStops>
		<stopFacility id="1-2" x="500" y="0" linkRefId="1-2" isBlocking="false">
		</stopFacility>
		<stopFacility id="7-8" x="500" y="-300" linkRefId="7-8" isBlocking="false">
		</stopFacility>
		<stopFacility id="14-15" x="500" y="-600" linkRefId="14-15" isBlocking="false">
		</stopFacility>
		<stopFacility id="5-6" x="30500" y="0" linkRefId="5-6" isBlocking="false">
		</stopFacility>
		<stopFacility id="12-13" x="30500" y="-300" linkRefId="12-13" isBlocking="false">
		</stopFacility>
		<stopFacility id="19-20" x="30500" y="-600" linkRefId="19-20" isBlocking="false">
		</stopFacility>
	</transitStops>
	<transitLine id="line1">
		<transitRoute id="line1_route1">
			<transportMode>rail</transportMode>
			<routeProfile>
				<stop refId="1-2" departureOffset="00:00:00" awaitDeparture="true"/>
				<stop refId="19-20" arrivalOffset="01:00:00" awaitDeparture="true"/>
			</routeProfile>
			<route>
				<link refId="1-2"/>
				<link refId="2-3"/>
				<link refId="3-9"/>
				<link refId="9-10"/>
				<link refId="10-17"/>
				<link refId="17-17a"/>
				<link refId="17a-17b"/>
				<link refId="17b-17c"/>
				<link refId="17c-18"/>
				<link refId="18-19"/>
				<link refId="19-20"/>
			</route>
			<departures>
				<departure id="0" departureTime="08:00:00" vehicleRefId="train1"/>
			</departures>
		</transitRoute>
	</transitLine>
	<transitLine id="line2">
		<transitRoute id="line2_route1">
			<transportMode>rail</transportMode>
			<routeProfile>
				<stop refId="7-8" departureOffset="00:00:00" awaitDeparture="true"/>
				<stop refId="12-13" arrivalOffset="01:00:00" awaitDeparture="true"/>
			</routeProfile>
			<route>
				<link refId="7-8"/>
				<link refId="8-9"/>
				<link refId="9-10"/>
				<link refId="10-11"/>
				<link refId="11-12"/>
				<link refId="12-13"/>
			</route>
			<departures>
				<departure id="0" departureTime="08:01:20" vehicleRefId="train2"/>
			</departures>
		</transitRoute>
	</transitLine>
</transitSchedule>

=== matsim-org/matsim-libs/input/uam/uam_stops.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE transitSchedule SYSTEM "http://www.matsim.org/files/dtd/transitSchedule_v2.dtd">

<transitSchedule>

	<transitStops>
		<stopFacility id="STOP_HUB_0" x="568690.0049580961" y="5812546.609416321" linkRefId="HUB_0" isBlocking="false"/>
		<stopFacility id="STOP_HUB_1" x="564418.2811688676" y="5780667.55214392" linkRefId="HUB_1" isBlocking="false"/>
		<stopFacility id="STOP_HUB_2" x="525507.990424061" y="5799269.937021481" linkRefId="HUB_2" isBlocking="false"/>
		<stopFacility id="STOP_HUB_3" x="528585.9346217033" y="5808749.889772218" linkRefId="HUB_3" isBlocking="false"/>
		<stopFacility id="STOP_HUB_4" x="542456.2902004212" y="5836851.520141924" linkRefId="HUB_4" isBlocking="false"/>
		<stopFacility id="STOP_HUB_5" x="550413.0624197081" y="5803301.803610637" linkRefId="HUB_5" isBlocking="false"/>
	</transitStops>
</transitSchedule>

=== matsim-org/matsim-libs/contribs/railsim/test/input/ch/sbb/matsim/contrib/railsim/integration/ring/transitSchedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE transitSchedule SYSTEM "http://www.matsim.org/files/dtd/transitSchedule_v2.dtd">
<transitSchedule>
	<transitStops>
		<stopFacility id="stop_North" x="-4700.0" y="10000.0" linkRefId="station_North" isBlocking="false" />
		<stopFacility id="stop_East" x="10000.0" y="4700.0" linkRefId="station_East" isBlocking="false" />
		<stopFacility id="stop_South" x="4700.0" y="-10000.0" linkRefId="station_South" isBlocking="false" />
		<stopFacility id="stop_West" x="-10000.0" y="-4700.0" linkRefId="station_West" isBlocking="false" />
	</transitStops>
	<transitLine id="line_1">
		<transitRoute id="route_1">
			<transportMode>rail</transportMode>
			<routeProfile>
				<stop refId="stop_South" departureOffset="00:00:00" arrivalOffset="00:00:00" awaitDeparture="true" />
				<stop refId="stop_West" departureOffset="00:15:00" arrivalOffset="00:15:00" awaitDeparture="true" />
				<stop refId="stop_North" departureOffset="00:30:00" arrivalOffset="00:30:00" awaitDeparture="true" />
				<stop refId="stop_East" departureOffset="00:45:00" arrivalOffset="00:45:00" awaitDeparture="true" />
				<stop refId="stop_South" arrivalOffset="01:00:00" awaitDeparture="true" />
			</routeProfile>
			<route>
				<!-- Ring route: South -> West -> North -> East -->
				<link refId="station_South" />
				<link refId="link_South" />
				<link refId="link_SouthWest" />
				<link refId="station_West" />
				<link refId="link_West" />
				<link refId="link_WestNorth" />
				<link refId="station_North" />
				<link refId="link_North" />
				<link refId="link_NorthEast" />
				<link refId="station_East" />
				<link refId="link_East" />
				<link refId="link_EastSouth" />
				<link refId="station_South" />
			</route>
			<departures>
				<departure id="dep_1" departureTime="00:00:00" vehicleRefId="train_1" />
				<departure id="dep_2" departureTime="01:00:00" vehicleRefId="train_1" />
				<departure id="dep_3" departureTime="02:00:00" vehicleRefId="train_1" />
				<departure id="dep_4" departureTime="03:00:00" vehicleRefId="train_1" />
				<departure id="dep_5" departureTime="04:00:00" vehicleRefId="train_1" />
			</departures>
		</transitRoute>
	</transitLine>
</transitSchedule>
