=== matsim-org/matsim-libs/matsim/src/main/resources/dtd/vehicleDefinitions_v2.0.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.matsim.org/files/dtd" xmlns="http://www.matsim.org/files/dtd"
           elementFormDefault="qualified"
           xml:lang="en">
    <!-- Editor: Kai Martins-Turner, VSP, Berlin Institute of Technology -->
    <!-- This xml schema contains xml definitions for vehicles and vehicleTypes in the MATSim framework  -->

    <xs:include schemaLocation="http://www.matsim.org/files/dtd/matsimCommon.xsd"/>
    <xs:include schemaLocation="http://www.matsim.org/files/dtd/vehicleDefinitionsEnumTypes.xsd"/>

    <xs:element name="vehicleDefinitions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vehicleType" type="vehicleTypeType" maxOccurs="unbounded"/>
                <xs:element name="vehicle" type="vehicleDefType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="vehicleTypeType">
        <xs:complexContent>
            <xs:extension base="matsimObjectType">
                <xs:sequence>
                    <xs:element name="attributes" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="attribute" type="attributeType" minOccurs="0" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="description" type="xs:string" minOccurs="0"/>
                    <xs:element name="capacity" type="capacityType" minOccurs="0"/>
                    <xs:element name="length" minOccurs="0">
                        <xs:complexType>
                            <xs:attribute name="meter" type="xs:decimal" default="7.5"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="width" minOccurs="0">
                        <xs:complexType>
                            <xs:attribute name="meter" type="xs:decimal" default="1"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="maximumVelocity" minOccurs="0">
                        <xs:complexType>
                            <xs:attribute name="meterPerSecond" type="xs:double" default="INF"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="engineInformation" type="engineInformationType" minOccurs="0"/>
                    <xs:element name="costInformation" type="costInformationType" minOccurs="0"/>
                    <xs:element name="passengerCarEquivalents" minOccurs="0">
                        <xs:complexType>
                            <xs:attribute name="pce" type="xs:decimal" default="1.0"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="networkMode" minOccurs="0">
                        <xs:complexType>
                            <xs:attribute name="networkMode" type="xs:string"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="flowEfficiencyFactor" minOccurs="0">
                        <xs:complexType>
                            <xs:attribute name="factor" type="xs:decimal" default="1.0"/>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="capacityType">
        <xs:sequence>
            <xs:element name="attributes" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="attribute" type="attributeType" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="seats" type="xs:nonNegativeInteger"/>
        <xs:attribute name="standingRoomInPersons" type="xs:nonNegativeInteger"/>
        <xs:attribute name="volumeInCubicMeters" type="xs:double"/>
        <xs:attribute name="weightInTons" type="xs:double"/>
        <xs:attribute name="other" type="xs:double"/>
    </xs:complexType>

    <xs:complexType name="engineInformationType">
        <xs:sequence>
            <xs:element name="attributes" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="attribute" type="attributeType" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="costInformationType">
        <xs:sequence>
            <xs:element name="attributes" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="attribute" type="attributeType" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="fixedCostsPerDay" type="xs:double"/>
        <xs:attribute name="costsPerMeter" type="xs:double"/>
        <xs:attribute name="costsPerSecond" type="xs:double"/>
    </xs:complexType>


    <xs:complexType name="vehicleDefType">
        <xs:annotation>
            <xs:documentation/>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="matsimObjectType">
                <xs:sequence>
                    <xs:element name="attributes" minOccurs="0" maxOccurs="1">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="attribute" type="attributeType" minOccurs="0" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
                <xs:attribute name="type" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== matsim-org/matsim-libs/examples/scenarios/mielec/etaxis-25.xml
<?xml version="1.0" encoding="UTF-8"?>

<vehicleDefinitions xmlns="http://www.matsim.org/files/dtd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.matsim.org/files/dtd http://www.matsim.org/files/dtd/vehicleDefinitions_v2.0.xsd">

	<vehicleType id="EV_20.0kWh">

		<capacity seats="0" standingRoomInPersons="0">

		</capacity>
		<length meter="7.5"/>
		<width meter="1.0"/>
		<engineInformation>
			<attributes>
				<attribute name="chargerTypes" class="java.util.ImmutableCollections$List12">["default"]</attribute>
				<attribute name="energyCapacityInKWhOrLiters" class="java.lang.Double">20.0</attribute>
				<attribute name="HbefaTechnology" class="java.lang.String">electricity</attribute>
			</attributes>
		</engineInformation>
		<costInformation>

		</costInformation>
		<passengerCarEquivalents pce="1.0"/>
		<networkMode networkMode="car"/>
		<flowEfficiencyFactor factor="1.0"/>
	</vehicleType>

	<vehicle id="taxi_1_1" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">16.0</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_1_2" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">14.0</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_1_3" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">12.0</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_1_4" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">10.0</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_1_5" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">8.0</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_2_1" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">15.5</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_2_2" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">13.5</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_2_3" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">11.5</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_2_4" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">9.5</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_2_5" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">7.5</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_3_1" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">15.0</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_3_2" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">13.0</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_3_3" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">11.0</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_3_4" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">9.0</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_3_5" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">7.0</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_4_1" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">14.5</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_4_2" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">12.5</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_4_3" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">10.5</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_4_4" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">8.5</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_4_5" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">6.5</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_5_1" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">14.0</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_5_2" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">12.0</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_5_3" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">10.0</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_5_4" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">8.0</attribute>
		</attributes>
	</vehicle>
	<vehicle id="taxi_5_5" type="EV_20.0kWh">
		<attributes>
			<attribute name="initialEnergyInKWh" class="java.lang.Double">6.0</attribute>
		</attributes>
	</vehicle>
		

</vehicleDefinitions>

=== matsim-org/matsim-libs/contribs/freight/test/input/org/matsim/freight/carriers/analysis/CarriersAnalysisTest/runServiceEventTest/in/output_allVehicles.xml
<?xml version="1.0" encoding="UTF-8"?>

<vehicleDefinitions xmlns="http://www.matsim.org/files/dtd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.matsim.org/files/dtd http://www.matsim.org/files/dtd/vehicleDefinitions_v2.0.xsd">

	<vehicleType id="heavy">

		<description>A heavy truck</description>
		<capacity seats="1" standingRoomInPersons="0" other="50.0">

		</capacity>
		<length meter="7.5"/>
		<width meter="1.0"/>
		<costInformation fixedCostsPerDay="130.0" costsPerMeter="7.7E-4" costsPerSecond="0.008">

		</costInformation>
		<passengerCarEquivalents pce="1.0"/>
		<networkMode networkMode="car"/>
		<flowEfficiencyFactor factor="1.0"/>
	</vehicleType>

	<vehicle id="freight_carrier1_veh_carrier_19_heavyVehicle_1" type="heavy"/>
		

</vehicleDefinitions>

=== matsim-org/matsim-libs/contribs/freight/test/input/org/matsim/freight/carriers/CarrierModuleTest/vehicleTypes.xml
<?xml version="1.0" encoding="UTF-8"?>

<vehicleDefinitions xmlns="http://www.matsim.org/files/dtd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.matsim.org/files/dtd http://www.matsim.org/files/dtd/vehicleDefinitions_v2.0.xsd">

	<vehicleType id="light">

		<description>Light Vehicle</description>
		<capacity seats="1" standingRoomInPersons="0" other="15.0">

		</capacity>
		<length meter="7.5"/>
		<width meter="1.0"/>
		<costInformation fixedCostsPerDay="20.0" costsPerMeter="0.35" costsPerSecond="30.0">

		</costInformation>
		<passengerCarEquivalents pce="1.0"/>
		<networkMode networkMode="car"/>
		<flowEfficiencyFactor factor="1.0"/>
	</vehicleType>

	<vehicleType id="medium">

		<description>Medium Vehicle</description>
		<capacity seats="1" standingRoomInPersons="0" other="30.0">

		</capacity>
		<length meter="7.5"/>
		<width meter="1.0"/>
		<costInformation fixedCostsPerDay="50.0" costsPerMeter="0.4" costsPerSecond="30.0">

		</costInformation>
		<passengerCarEquivalents pce="1.0"/>
		<networkMode networkMode="car"/>
		<flowEfficiencyFactor factor="1.0"/>
	</vehicleType>

		

</vehicleDefinitions>

=== matsim-org/matsim-libs/contribs/railsim/test/input/ch/sbb/matsim/contrib/railsim/integration/abzweigung/vehicles.xml
<?xml version="1.0" encoding="UTF-8"?>
<vehicleDefinitions xmlns="http://www.matsim.org/files/dtd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.matsim.org/files/dtd http://www.matsim.org/files/dtd/vehicleDefinitions_v2.0.xsd">
	<vehicleType id="FV">
		<attributes>
			<attribute class="java.lang.Double" name="accessTimeInSecondsPerPerson">0.0</attribute>
			<attribute class="java.lang.Double" name="egressTimeInSecondsPerPerson">0.0</attribute>
			<attribute class="java.lang.Double" name="railsimAcceleration">0.6</attribute>
			<attribute class="java.lang.Double" name="railsimDeceleration">0.7</attribute>
		</attributes>
		<capacity seats="9999" standingRoomInPersons="9999" />
		<length meter="400.0" />
		<width meter="1.0" />
		<maximumVelocity meterPerSecond="44.444" />
		<costInformation />
		<passengerCarEquivalents pce="0.0" />
		<networkMode networkMode="rail" />
		<flowEfficiencyFactor factor="1.0" />
	</vehicleType>
	<vehicleType id="GV">
		<attributes>
			<attribute class="java.lang.Double" name="accessTimeInSecondsPerPerson">0.0</attribute>
			<attribute class="java.lang.Double" name="egressTimeInSecondsPerPerson">0.0</attribute>
			<attribute class="java.lang.Double" name="railsimAcceleration">0.2</attribute>
			<attribute class="java.lang.Double" name="railsimDeceleration">0.4</attribute>
		</attributes>
		<capacity seats="9999" standingRoomInPersons="9999" />
		<length meter="400.0" />
		<width meter="1.0" />
		<maximumVelocity meterPerSecond="27.7778" />
		<costInformation />
		<passengerCarEquivalents pce="0.0" />
		<networkMode networkMode="rail" />
		<flowEfficiencyFactor factor="1.0" />
	</vehicleType>
	<vehicleType id="RV">
		<attributes>
			<attribute class="java.lang.Double" name="accessTimeInSecondsPerPerson">0.0</attribute>
			<attribute class="java.lang.Double" name="egressTimeInSecondsPerPerson">0.0</attribute>
			<attribute class="java.lang.Double" name="railsimAcceleration">1.0</attribute>
			<attribute class="java.lang.Double" name="railsimDeceleration">0.7</attribute>
		</attributes>
		<capacity seats="9999" standingRoomInPersons="9999" />
		<length meter="200.0" />
		<width meter="1.0" />
		<maximumVelocity meterPerSecond="44.444" />
		<costInformation />
		<passengerCarEquivalents pce="0.0" />
		<networkMode networkMode="rail" />
		<flowEfficiencyFactor factor="1.0" />
	</vehicleType>
	<vehicle id="FV_AB" type="FV" />
	<vehicle id="FV_BA" type="FV" />
	<vehicle id="FV_AC" type="FV" />
	<vehicle id="FV_CA" type="FV" />
	<vehicle id="GV_AB" type="GV" />
	<vehicle id="GV_BA" type="GV" />
	<vehicle id="GV_AC" type="GV" />
	<vehicle id="GV_CA" type="GV" />
	<vehicle id="RV_AB" type="RV" />
	<vehicle id="RV_BA" type="RV" />
	<vehicle id="RV_AC" type="RV" />
	<vehicle id="RV_CA" type="RV" />
</vehicleDefinitions>

=== matsim-org/matsim-libs/contribs/railsim/test/input/ch/sbb/matsim/contrib/railsim/integration/microStationReroutingTwoDirections/transitVehicles.xml
<?xml version="1.0" encoding="UTF-8"?>

<vehicleDefinitions xmlns="http://www.matsim.org/files/dtd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.matsim.org/files/dtd http://www.matsim.org/files/dtd/vehicleDefinitions_v2.0.xsd">

	<vehicleType id="FV_Dosto">
		<attributes>
			<attribute name="railsimAcceleration" class="java.lang.Double">0.5</attribute>
			<attribute name="railsimMaxDeceleration" class="java.lang.Double">0.5</attribute>
		</attributes>
		<capacity seats="9999" standingRoomInPersons="9999">
		</capacity>
		<length meter="750.0"/>
		<width meter="1.0"/>
		<maximumVelocity meterPerSecond="27.7778"/>
		<costInformation>
		</costInformation>
		<passengerCarEquivalents pce="1.0"/>
		<networkMode networkMode="rail"/>
		<flowEfficiencyFactor factor="1.0"/>
	</vehicleType>
	<vehicleType id="RE_Flirt">
		<attributes>
			<attribute name="railsimAcceleration" class="java.lang.Double">0.7</attribute>
			<attribute name="railsimMaxDeceleration" class="java.lang.Double">0.7</attribute>
		</attributes>
		<capacity seats="9999" standingRoomInPersons="9999">
		</capacity>
		<length meter="500.0"/>
		<width meter="1.0"/>
		<maximumVelocity meterPerSecond="13.889"/>
		<costInformation>
		</costInformation>
		<passengerCarEquivalents pce="1.0"/>
		<networkMode networkMode="rail"/>
		<flowEfficiencyFactor factor="1.0"/>
	</vehicleType>
	
	<vehicle id="IC_BO_0" type="FV_Dosto"/>
	<vehicle id="IC_BO_1" type="FV_Dosto"/>
	<vehicle id="IC_BO_2" type="FV_Dosto"/>
	<vehicle id="IC_BO_3" type="FV_Dosto"/>
	<vehicle id="IC_BU_0" type="FV_Dosto"/>
	<vehicle id="IC_BU_1" type="FV_Dosto"/>
	<vehicle id="IC_BU_2" type="FV_Dosto"/>
	<vehicle id="IC_BU_3" type="FV_Dosto"/>

	<vehicle id="RE_BO_0" type="RE_Flirt"/>
	<vehicle id="RE_BO_1" type="RE_Flirt"/>
	<vehicle id="RE_BO_2" type="RE_Flirt"/>
	<vehicle id="RE_BO_3" type="RE_Flirt"/>
	<vehicle id="RE_BU_0" type="RE_Flirt"/>
	<vehicle id="RE_BU_1" type="RE_Flirt"/>
	<vehicle id="RE_BU_2" type="RE_Flirt"/>
	<vehicle id="RE_BU_3" type="RE_Flirt"/>

</vehicleDefinitions>

=== matsim-org/matsim-libs/contribs/freight/test/input/org/matsim/freight/carriers/vehicleTypes_v2.xml
<?xml version="1.0" encoding="UTF-8"?>

<vehicleDefinitions xmlns="http://www.matsim.org/files/dtd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.matsim.org/files/dtd http://www.matsim.org/files/dtd/vehicleDefinitions_v2.0.xsd">

	<vehicleType id="heavy">

		<description>Medium Vehicle</description>
		<capacity seats="0" standingRoomInPersons="0" other="30.0">

		</capacity>
		<length meter="7.5"/>
		<width meter="1.0"/>
		<engineInformation>
			<attributes>
				<attribute name="HbefaTechnology" class="java.lang.String">gasoline</attribute>
				<attribute name="fuelConsumptionLitersPerMeter" class="java.lang.Double">0.03</attribute>
			</attributes>
		</engineInformation>
		<costInformation fixedCostsPerDay="100.0" costsPerMeter="0.45" costsPerSecond="30.0">

		</costInformation>
		<passengerCarEquivalents pce="1.0"/>
		<networkMode networkMode="car"/>
		<flowEfficiencyFactor factor="1.0"/>
	</vehicleType>

	<vehicleType id="light">

		<description>Light Vehicle</description>
		<capacity seats="0" standingRoomInPersons="0" other="15.0">

		</capacity>
		<length meter="7.5"/>
		<width meter="1.0"/>
		<engineInformation>
			<attributes>
				<attribute name="HbefaTechnology" class="java.lang.String">gasoline</attribute>
				<attribute name="fuelConsumptionLitersPerMeter" class="java.lang.Double">0.02</attribute>
			</attributes>
		</engineInformation>
		<costInformation fixedCostsPerDay="20.0" costsPerMeter="0.35" costsPerSecond="30.0">

		</costInformation>
		<passengerCarEquivalents pce="1.0"/>
		<networkMode networkMode="car"/>
		<flowEfficiencyFactor factor="1.0"/>
	</vehicleType>

	<vehicleType id="medium">

		<description>Medium Vehicle</description>
		<capacity seats="0" standingRoomInPersons="0" other="30.0">

		</capacity>
		<length meter="7.5"/>
		<width meter="1.0"/>
		<engineInformation>
			<attributes>
				<attribute name="HbefaTechnology" class="java.lang.String">gasoline</attribute>
				<attribute name="fuelConsumptionLitersPerMeter" class="java.lang.Double">0.02</attribute>
			</attributes>
		</engineInformation>
		<costInformation fixedCostsPerDay="50.0" costsPerMeter="0.4" costsPerSecond="30.0">

		</costInformation>
		<passengerCarEquivalents pce="1.0"/>
		<networkMode networkMode="car"/>
		<flowEfficiencyFactor factor="1.0"/>
	</vehicleType>



</vehicleDefinitions>
